### ISSUE TITLE
Proton installation could not be found due to config.vdf casing

### ISSUE THREAD

**Issue by EvoSteven** [Matoking/protontricks#104]
Protontricks wouldn't work for me initially and it seems like both `valve` and `steam` were lowercase in my `config.vdf`, which didn't work with what protontricks expected (`vdf_data["InstallConfigStore"]["Software"]["Valve"]["Steam"]`).

Changing those to be properly cased in the vdf file made it work for me.
Not sure what caused this or how common it is but figured I should report it all the same.

**Comment by Matoking** [comment]
The new Steam beta came with multiple breaking changes: many VDF fields are now lowercase and the structure of `libraryfolders.vdf` is now different. I've pushed changes to `vdf_all_lowercase` branch that should hopefully resolve all the new issues.

You can install and test the fixes by installing Protontricks using pipx. You can check the README and follow the instructions for the most part, but use the following `pipx install` command instead:

```
$ pipx install --force git+https://github.com/Matoking/protontricks.git@vdf_all_lowercase
```

Could you check whether this lets you run Protontricks properly again?

**Comment by EvoSteven** [comment]
Great! Tested it and the `vdf_all_lowercase` branch seems to work on my end.

**Comment by Matoking** [comment]
Good, I'll merge the fix into master. Thanks for the help!

**Comment by fuzunspm** [comment]
I'm getting below error on pipx command

```
Traceback (most recent call last):
  File "/usr/bin/pipx", line 33, in <module>
    sys.exit(load_entry_point('pipx==0.16.4', 'console_scripts', 'pipx')())
  File "/usr/lib/python3.9/site-packages/pipx/main.py", line 765, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/usr/lib/python3.9/site-packages/pipx/main.py", line 193, in run_pipx_command
    return commands.install(
  File "/usr/lib/python3.9/site-packages/pipx/commands/install.py", line 30, in install
    package_name = package_name_from_spec(
  File "/usr/lib/python3.9/site-packages/pipx/commands/common.py", line 333, in package_name_from_spec
    package_name = venv.install_package_no_deps(
  File "/usr/lib/python3.9/site-packages/pipx/venv.py", line 268, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/usr/lib/python3.9/site-packages/pipx/venv.py", line 348, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
