### ISSUE TITLE
Any protontricks command fails with KeyError: 'LibraryFolders'`

### ISSUE THREAD

**Issue by EduFrazao** [Matoking/protontricks#108]
**Describe the bug**
I can't run any protontricks command. Any commands like "protontricks -s game" fails with

`Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==0.0.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 177, in main
    steam_lib_paths = get_steam_lib_paths(steam_path)
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 616, in get_steam_lib_paths
    library_folders = parse_library_folders(folders_vdf_path.read_text())
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 600, in parse_library_folders
    Path(value) for key, value in vdf_data["LibraryFolders"].items()
KeyError: 'LibraryFolders'`

**To Reproduce**
1. Run command `protontricks -s game`
2. Command fails and error is displayed

**Expected behavior**
Show the list of found games 

**System (please complete the following information):**
 - Distro: Gentoo Linux, Kernel 5.12.10, Python 3.9
 - Protontricks version: run `protontricks --version`
 `eduardo ~ $ protontricks --version
protontricks (1.5.1)`

 - Steam version: Launcher 1.0.0.70, SteamPackage versions: 2623445000

**Comment by EduFrazao** [comment]
Solved with version 1.5.2
