### ISSUE TITLE
Protontricks does not start.

### ISSUE THREAD

**Issue by FlookyMonster** [Matoking/protontricks#131]
**Describe the bug**
Protontricks does not start.

**To Reproduce**
1. Run any command, it won't even launch.

**Expected behavior**
Protontricks to show up and letting me choose a game.

**System (please complete the following information):**
 - Distro: Manjaro Linux
 - Protontricks version: as i said it wont even let me check that
 - Steam version: idk

**Additional context**

Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.6.3.dev4+gace4189', 'console_scripts', 'protontricks')())
  File "/usr/bin/protontricks", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: protontricks

**Comment by Matoking** [comment]
Arch Linux recently upgraded from Python 3.9 to 3.10, and Manjaro has also received this update now. You'll need to rebuild any Python packages you've installed from AUR, in this case _protontricks_ **and** _python-vdf_. You can check the instructions here for rebuilding all lingering Python packages here:

https://wiki.manjaro.org/index.php/Python_upgrade#AUR
https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/

**Comment by Matoking** [comment]
Closing issue due to inactivity.
