### ISSUE TITLE
SyntaxError: Unknown data type at index 9: b'a'

### ISSUE THREAD

**Issue by IanTrudel** [Matoking/protontricks#148]
The following is happening on any games that I would select.

- Python 3.6.8
- protontricks (1.8.2.dev3+gbe3805b)
- winetricks 20220411-next - sha256sum: d23dbdf84a2f75b0cbb9608f9ba9d65ee23947fdf71be76115c9eb066b3b3100

```
protontricks --gui
Traceback (most recent call last):
  File "/home/ian/.local/bin/protontricks", line 8, in <module>
    sys.exit(cli())
  File "/home/ian/.local/pipx/venvs/protontricks/lib64/python3.6/site-packages/protontricks/cli/main.py", line 30, in cli
    main(args)
  File "/home/ian/.local/pipx/venvs/protontricks/lib64/python3.6/site-packages/protontricks/cli/util.py", line 148, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/home/ian/.local/pipx/venvs/protontricks/lib64/python3.6/site-packages/protontricks/cli/main.py", line 249, in main
    steam_path=steam_path, steam_apps=steam_apps, appid=steam_app.appid
  File "/home/ian/.local/pipx/venvs/protontricks/lib64/python3.6/site-packages/protontricks/steam.py", line 718, in find_proton_app
    steam_path=steam_path, steam_apps=steam_apps, appid=appid)
  File "/home/ian/.local/pipx/venvs/protontricks/lib64/python3.6/site-packages/protontricks/steam.py", line 506, in find_steam_compat_tool_app
    section for section in iter_appinfo_sections(appinfo_path)
  File "/home/ian/.local/pipx/venvs/protontricks/lib64/python3.6/site-packages/protontricks/steam.py", line 506, in <listcomp>
    section for section in iter_appinfo_sections(appinfo_path)
  File "/home/ian/.local/pipx/venvs/protontricks/lib64/python3.6/site-packages/protontricks/steam.py", line 428, in iter_appinfo_sections
    vdf_d = vdf.binary_loads(data[i:i+vdf_section_size])
  File "/home/ian/.local/pipx/venvs/protontricks/lib64/python3.6/site-packages/vdf/__init__.py", line 366, in binary_loads
    raise SyntaxError("Unknown data type at index %d: %s" % (idx-1, repr(t)))
SyntaxError: Unknown data type at index 9: b'a'
```

**Comment by Matoking** [comment]
I'm unable to reproduce this on Steam Beta (built on May 2 2022, at 17:46:48). You can check the Steam version at Help -> About Steam, and whether you are rolled into Steam beta under Settings -> Account -> Beta participation. Please add those into a reply as it may help narrow down the cause.

Before that, we could try to rule out `appinfo.vdf` being corrupted, albeit that is unlikely. To check this, close Steam, then open the directory `/home/ian/.steam/steam/appcache/` in a file browser and either delete `appinfo.vdf` or rename it. Restart Steam and wait until the file reappears, and then try running Protontricks again.

**Comment by IanTrudel** [comment]
Hmmm. I had the same Steam Beta but updated to May 10 2022, at 16:13:12 and removed appinfo.vdf. Protontricks seems to be working now. Gave it a spin and installed a few things and ran winecfg. What a world we live in, what a world.
