### ISSUE TITLE
Protontricks failed to just open. 

### ISSUE THREAD

**Issue by Desertwolf89** [Matoking/protontricks#167]
I get this error and I'm not sure how to fix it. 

Protontricks was closed due to the following error:

Traceback (most recent call last):

File "/app/lib/python3.9/site-packages/protontricks/cli/util.py", line 148, in wrapper

return cli_func(self, *args, **kwargs)

File "/app/lib/python3.9/site-packages/protontricks/cli/main.py", line 228, in main

steam_apps = get_steam_apps(

File "/app/lib/python3.9/site-packages/protontricks/steam.py", line 1145, in get_steam_apps

steam_app = SteamApp.from_appmanifest(

File "/app/lib/python3.9/site-packages/protontricks/steam.py", line 189, in from_appmanifest

content = path.read_text(encoding="utf-8")

File "/usr/lib/python3.9/pathlib.py", line 1266, in read_text

with self.open(mode='r', encoding=encoding, errors=errors) as f:

File "/usr/lib/python3.9/pathlib.py", line 1252, in open

return io.open(self, mode, buffering, encoding, errors, newline,

File "/usr/lib/python3.9/pathlib.py", line 1120, in _opener

return self._accessor.open(self, flags, mode)

OSError: [Errno 117] Structure needs cleaning: '/run/media/mmcblk0p1/steamapps/appmanifest_1968730.acf'

=============

Please include this entire error message when making a bug report.

Log messages:

Running inside Flatpak sandbox, version 1.12.4.

Found Steam directory at /home/deck/.local/share/Steam

Using Steam directory at /home/deck/.local/share/Steam. You can also define Steam directory manually using $STEAM_DIR

Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime

WINETRICKS environment variable is not available. Searching from $PATH.

Found 2 Steam library folders

**Comment by Desertwolf89** [comment]
I clean installed steam and the error still pops up. Didn't wipe the sd card though. Any advice?

**Comment by Matoking** [comment]
Closing due to inactivity.
