### ISSUE TITLE
protontricks error on steam deck

### ISSUE THREAD

**Issue by FASTRACER023** [Matoking/protontricks#183]
whenever i try to run a protontricks command in konsole i get this error :

protontricks (ERROR): 'winetricks' executable could not be found automatically.
Winetricks isn't installed, please install winetricks in order to use this script! 

what do i do? i tried installing protontricks both through discover and konsole but no luck.

**Comment by Matoking** [comment]
What do you mean by "installing it through Konsole"? Did you use `pipx`, `pacman` or something else? What distro are you using?

For the Flatpak version, the command-line version is not available through `protontricks` just by installing it. You'll also have to setup an alias [as described here](https://github.com/flathub/com.github.Matoking.protontricks#installation). Alternatively, you can substitute `protontricks` for `flatpak run com.github.Matoking.protontricks` which does the same thing. For example, instead of running

```
protontricks 1234 foo
```

just run

```
flatpak run com.github.Matoking.protontricks 1234 foo
```

**Comment by FASTRACER023** [comment]
> What do you mean by "installing it through Konsole"? Did you use `pipx`, `pacman` or something else? What distro are you using?
> 
> For the Flatpak version, the command-line version is not available through `protontricks` just by installing it. You'll also have to setup an alias [as described here](https://github.com/flathub/com.github.Matoking.protontricks#installation). Alternatively, you can substitute `protontricks` for `flatpak run com.github.Matoking.protontricks` which does the same thing. For example, instead of running
> 
> ```
> protontricks 1234 foo
> ```
> 
> just run
> 
> ```
> flatpak run com.github.Matoking.protontricks 1234 foo
> ```

hi, thanks for the reply.

i used pacman to install through konsole and i'm also on steamos, since im on steamdeck

your suggestion worked but i'm still having trouble with winecfg command. any suggestions?

**Comment by Matoking** [comment]
I need more information than that. What are you trying to do (eg. what is the command), and what is happening instead?

**Comment by FASTRACER023** [comment]
i'm following a tutorial for a game and one of the commands is

$ flatpak run com.github.Matoking.protontricks -c winecfg 244210

the output was along the lines of winecfg on recognized as command

**Comment by Matoking** [comment]
Try the following command instead:

```
flatpak run com.github.Matoking.protontricks -c "wine winecfg" 244210
```

Alternatively, start Protontricks -> select the game -> select "Select the default wineprefix" -> "Run winecfg", which should do the same thing.

**Comment by HellishINC** [comment]
I'm getting the a similar error message though I'm using flatpak on Gentoo.

```
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 234, in main
    prompt_filesystem_access(
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 372, in prompt_filesystem_access
    inaccessible_paths = get_inaccessible_paths(paths)
  File "/app/lib/python3.10/site-packages/protontricks/flatpak.py", line 167, in get_inaccessible_paths
    mounted_paths = [_map_path(path) for path in mounted_paths]
  File "/app/lib/python3.10/site-packages/protontricks/flatpak.py", line 167, in <listcomp>
    mounted_paths = [_map_path(path) for path in mounted_paths]
  File "/app/lib/python3.10/site-packages/protontricks/flatpak.py", line 134, in _map_path
    if path.startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'


=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.3.
Found Steam directory at /home/shelly/.var/app/com.valvesoftware.Steam/.local/share/Steam
Using default Steam Runtime at /home/shelly/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
```

When trying to run from term I get

```
flatpak run com.github.Matoking.protontrick -c winecfg 1245620
error: app/com.github.Matoking.protontrick/x86_64/master not installed
```

I see there are other (though unhelpful) reviews on `discover` also stating it does not launch.

If this is a different issue please let me know and I'll create a new one and remove this post.

**Comment by Matoking** [comment]
@HellishINC Whoops, that was a bug introduced in 1.10.0. I've pushed a fix to Flathub that should go live in a few hours.

**Comment by Matoking** [comment]
Closing issue due to inactivity.

**Comment by stiinkyratz** [comment]
i cant run the commands listed to fix the protontricks bug 

(deck@steamdeck ~)$ flatpak update --commit=fab6248ad1c2c8fc59a45c1cfc8cce914a759e1c68373d82ea1c03e0f75b9098 com.github.Matoking.protontricks
Looking for updates…
error: Server returned status 404
(1)(deck@steamdeck ~)$
