### ISSUE TITLE
Crashes when i try to use a Steam ID

### ISSUE THREAD

**Issue by OSuKaRuXD** [Matoking/protontricks#191]
now suddenly it crashes  when it tries to use a Steam App ID. Protontricks --gui works and show me all the IDs but, when i try to open any of my IDs it crashes. Same if i do the command directly without the GUI. It promps me with this:

Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

I tried reinstalling and delleting the IDs. I don't know where could be the problem.

**Comment by JohnnyKarate2** [comment]
I have the exact same problem and almost the same stacktrack:

Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.9.2', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.10/site-packages/protontricks/cli/main.py", line 30, in cli
    main(args)
  File "/usr/lib/python3.10/site-packages/protontricks/cli/util.py", line 148, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/protontricks/cli/main.py", line 317, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 740, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 528, in find_steam_compat_tool_app
    appinfo_sections = [
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 528, in <listcomp>
    appinfo_sections = [
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 436, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

**Comment by JohnnyKarate2** [comment]
Updating protontricks to the newest version (1.10.0) did not resolve the issue

**Comment by Matoking** [comment]
The AUR package on `protontricks` has to be updated to use the latest release. As a workaround, try `protontricks-git` for the time being.
