### ISSUE TITLE
Protontricks dont wprk on steamdeck

### ISSUE THREAD

**Issue by Pashtetishe** [Matoking/protontricks#199]
**Describe the bug**
Im trying to add xaudio2_6 and xaudio2_7 to my skyrim launcher skse, but window closed with error

**System (please complete the following information):**
 - Distro: steamos
 - Protontricks installation method: dont know how install it on steamdeck
 - Protontricks version: got it from discower rn
 - Steam version: steam deck stable

**Additional context**
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 370, in main
    returncode = run_command(
  File "/app/lib/python3.10/site-packages/protontricks/util.py", line 411, in run_command
    process = _start_process(
  File "/app/lib/python3.10/site-packages/protontricks/util.py", line 222, in _start_process
    process = Popen(args=args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/Games/Skyrim/The Elder Scrolls V Skyrim - Special Edition'

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/deck/.local/share/Steam
Found 1 Steam library folders
Currently logged-in Steam user: pashtet143
Found 6 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
Calling `protontricks` with the command: ['--no-term', '-c', "wine '/run/flatpak/doc/6fe8098a/skse64_loader.exe'", '2711724444']
Running inside Flatpak sandbox, version 1.12.4.
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: *******
Found 6 Steam shortcuts running using Steam compatibility tools
User has configured app Proton version (CompatToolMapping): proton_7
Found active compatibility tool: Proton 7.0
Active compatibility tool is a Proton installation
Using 'bwrap = True' as default value
Using 'background-wineserver = True' as default value
Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
Running Steam Runtime using bwrap containerization.
If any problems arise, please try running the command again using the `--no-bwrap` flag and make an issue report if the problem only occurs when bwrap is in use.
Created Steam Runtime Wine binary directory at /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin
WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
Starting bwrap launcher process: /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin/bwrap-launcher
Starting wineserver keepalive process: /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin/wineserver-keepalive
Attempting to run command wine '/run/flatpak/doc/6fe8098a/skse64_loader.exe'
Terminating wineserver keepalive process 28
Terminating launcher process 27
Launcher process terminated

**Comment by Matoking** [comment]
It seems like you're trying to access Skyrim that isn't installed via Steam? `/home/deck/Games` is managed by Heroic according to some googling I've done. If so, Protontricks might not be able to have access to the required files by default.

In this case, Protontricks does not have access to your entire home directory by default. You can enable access by installing and running Flatseal, selecting Protontricks and checking either "All user files" under "Filesystem", or adding new entry under "Other files" with text `~/Games`.

Protontricks does not have official support for games that are not managed by Steam, however, so there might be other issues. Still, hopefully this helps.

**Comment by Pashtetishe** [comment]
Yep, you right. My Skyrim isn`t installed via Steam. Its gog version from my PC.

Thank you for your advice!
Im install Flatseal and did what you say, but now nothing is happend.

I launch the winetricks app, select my game, the window closes and nothing else happens
It also happens vith all games installed via Steam.

**Comment by Matoking** [comment]
Closing old issue, please create a new issue if this is is still relevant.
