### ISSUE TITLE
Protontricks trying to read old directory path

### ISSUE THREAD

**Issue by JasminDreasond** [Matoking/protontricks#201]
A while ago I installed a partition for the first time to start using Steam. And I randomly used protontricks to read this old partition. When I found that I needed to change the partition format for proton to work correctly I did. I changed the name of the partition. But when I try to use protontricks to read some application, it thinks I'm still using the old path name. So this ends up causing file and folder not found errors.

All I need to know is just one simples question. How do I reset this cache of old path to read the new directory path?

**Comment by JasminDreasond** [comment]
I discovered the first step by myself. I had to delete the old path I mentioned inside this file:
/home/user/.local/share/Steam/config/libraryfolders.vdf

But now I still need to finish solving this here.

```
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 148, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 261, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 717, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 505, in find_steam_compat_tool_app
    appinfo_sections = [
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 505, in <listcomp>
    appinfo_sections = [
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 413, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number


=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/****/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/****/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Currently logged-in Steam user: ****
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'zenity' as GUI provider
```

**Comment by JasminDreasond** [comment]
okay. the ubuntu shop was installing the wrong version of the protontricks. I fixed this by myself. c:
