### ISSUE TITLE
[Linux Mint] Error when trying to open a game with the GUI

### ISSUE THREAD

**Issue by Axis4s** [Matoking/protontricks#204]
**Describe the bug**
I Tried Opening a game (Bayonetta) on the Gui but i got this error instead.

**Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 214, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/user/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/user/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: UserName
Couldn't find custom shortcuts. Maybe none have been created yet?
Using 'zenity' as GUI provider**

**To Reproduce**
1. Run Proton Tricks GUI

**Expected behavior**
I Expected it to open the window to select a config tool, such as regedit.

**System (please complete the following information):**
 - Distro: Linux Mint 21.1
 - Protontricks installation method: System Package
 - Protontricks version: protontricks (1.7.0)
 - Steam version: Steam Package Versions: 1675744383 (Yes i am on Steam Beta Update)

**Comment by Kateba72** [comment]
I had the same issue with protontricks 1.9.1. Upgrading to 1.10 solved the issue for me, so you might want to try that

**Comment by Matoking** [comment]
As the previous poster stated,  try updating your Protontricks installation. The newer Steam has changed the structure of the appinfo.vdf that Protontricks needs to parse; Protontricks was updated to support it in 1.10.1.

**Comment by JechtShinryaku** [comment]
Hi, I also having this problem of "Invalid file magic number" with 1.10.2 version.
I tried it too on my laptop and I get "You are running winetricks-20220411, lastest upstream  is winetricks-20230212"

I installed both with AUR "protontricks-git", so it should be the last version.

What is happennig?

**Comment by Matoking** [comment]
> Hi, I also having this problem of "Invalid file magic number" with 1.10.2 version. I tried it too on my laptop and I get "You are running winetricks-20220411, lastest upstream is winetricks-20230212"
> 
> I installed both with AUR "protontricks-git", so it should be the last version.
> 
> What is happennig?

What is the Steam version on the system that prints the "Invalid file magic number" message? You can check it in Steam under Help -> About Steam. On my system the current version is listed with a build date of "Mar 2 2023, at 23:52:21". I am unable to reproduce the error even if I remove the `steam/appcache/appinfo.vdf` file and restart Steam, which regenerates it.

The Winetricks error is caused by Arch still shipping an outdated version of Winetricks. You can try updating it manually per instructions here:

https://github.com/Winetricks/winetricks#installing

Alternatively, the Flatpak version of Protontricks comes with an up-to-date version of Winetricks.

**Comment by Matoking** [comment]
Closing due to inactivity.
