### ISSUE TITLE
Crash after selecting Steam app

### ISSUE THREAD

**Issue by freq-mod** [Matoking/protontricks#214]
```
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.9.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 30, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 148, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 261, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 717, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 505, in find_steam_compat_tool_app
    appinfo_sections = [
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 505, in <listcomp>
    appinfo_sections = [
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 413, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

```
Ubuntu 22.10, protontricks etc installed from apt.

**Comment by freq-mod** [comment]
The culprit was the ridiculously outdated program version. After switching to flatpak version it works fine.
