### ISSUE TITLE
Crash after selecting game using Zenity

### ISSUE THREAD

**Issue by albertgallego** [Matoking/protontricks#218]
**Describe the bug**
After selecting the intended game, the GUI crashes.

**To Reproduce**
1. Select the game
2. Observe the crash.

**Expected behavior**
Well, I expected it to work.

**System (please complete the following information):**
 - Distro: Mint 21 Vanessa
 - Protontricks installation method: apt
 - Protontricks version: 1.7

**Additional context**
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 214, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/albert/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/albert/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: [[USERNAME]]
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'zenity' as GUI provider

**Comment by Matoking** [comment]
The Protontricks version you have installed is too old; the current version is 1.10.2.

If the latest version isn't available in your distro's repository it's recommended to install the Flatpak version instead.
