### ISSUE TITLE
Protontricks was closed - error

### ISSUE THREAD

**Issue by KinkGD** [Matoking/protontricks#222]
When trying to start protontricks for a non steam game, just after picking the game in the list : 

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/home/kgd/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/cli/util.py", line 148, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/home/kgd/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/cli/main.py", line 248, in main
    proton_app = find_proton_app(
  File "/home/kgd/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 717, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/home/kgd/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 505, in find_steam_compat_tool_app
    appinfo_sections = [
  File "/home/kgd/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 505, in <listcomp>
    appinfo_sections = [
  File "/home/kgd/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 413, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/kgd/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/kgd/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 3 Steam library folders
Multiple compatdata directories found for app 8800
Multiple compatdata directories found for app 1601970
Multiple compatdata directories found for app 1326470
Multiple compatdata directories found for app 1605220
Multiple compatdata directories found for app 429570
Multiple compatdata directories found for app 815370
Multiple compatdata directories found for app 882100
Multiple compatdata directories found for app 1030840
Currently logged-in Steam user: k1-tal
Found 6 Steam shortcuts running using Steam compatibility tools
Using 'zenity' as GUI provider

--
ZorinOs 16.2

**Comment by Matoking** [comment]
Is your Protontricks installation up to date? You can update the pipx installation by running `pipx upgrade protontricks`.

The "Invalid magic number" error should be fixed starting with 1.10.1.

**Comment by davidak** [comment]
@Matoking can you make it a nicer error message without the stacktrace and also provide this hint to check for updates?

**Comment by Matoking** [comment]
Pushed a small fix to master to improve the error message; closing this issue.
