### ISSUE TITLE
Unable to open protontricks flatpak version on Steam Deck

### ISSUE THREAD

**Issue by RodoMa92** [Matoking/protontricks#239]
**Describe the bug**
Opening the last flatpak version from desktop mode on the Steam Deck blurts out this error log.
```
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 241, in main
    steam_apps = get_steam_apps(
  File "/app/lib/python3.10/site-packages/protontricks/steam.py", line 1249, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
  File "/app/lib/python3.10/site-packages/protontricks/steam.py", line 190, in from_appmanifest
    content = path.read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/deck/SamSD512/steamapps/appmanifest_466560.acf'
=============

Running inside Flatpak sandbox, version 1.14.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders 
```

The game that has the id of 466560 is Northgard, which I have recently uninstalled. If I reinstall it on the SD Card, it opens fine but it's only showing three games and not the 40+ (approximate number). If I remove the game again, Protontricks will fail again with the exact same error message. I have checked the library.vdf file but I do not see that app id after removal, as it should be.

Another small bug that I've noticed is if the icon associated with the game is bigger (sometimes people likes to download different artwork from the stock one), the space that the box takes is equal to the icon resolution, that destroy the table layout a little bit. If you could clamp it to a max of 64x64 (or similar), that would be really appreciated.

I've already tried to uninstall it and delete the app data and reinstall it to no avail.

**To Reproduce**
1. Open protontricks flatpak version
2. The error below show up

**Expected behavior**
It should open a list of installed games.

**System (please complete the following information):**
 - Distro: SteamOS main channel 20230630.1000
 - Protontricks installation method: Flatpak
 - Protontricks version: version 1.14.4
 - Steam version: Steam Beta Client

**Comment by Matoking** [comment]
This looks a bit weird: Protontricks retrieves a list of app manifest files and then reads each one. The read here is failing due to the file not being found after we first found it; I'm guessing it could be a symlink which is now pointing to a non-existent location?

Could you run the following commands in Konsole and copy the output for each command here?

```
$ ls -lh /run/media/deck/SamSD512/steamapps/appmanifest_466560.acf
$ ls -lh /run/media/deck/SamSD512/steamapps
$ ls -lh /run/media/deck/SamSD512
```

Assuming that's the case, we could treat it as yet another oddity that Steam tolerates without fixing it automatically.

Thanks for the heads up on the app selector layout getting messed up if there are icons of different sizes!

**Comment by RodoMa92** [comment]
Sorry for the delay, and yes, the second command show a link that points nowhere:
```sh
DeckDiMarco% ls -lh /run/media/deck/SamSD512/steamapps
ls: impossibile accedere a '/run/media/deck/SamSD512/steamapps/appmanifest_466560.acf': File o directory non esistente
totale 244K
-rwxr-xr-x 1 deck deck  656 13 lug 18.15 appmanifest_1070560.acf
-rwxr-xr-x 1 deck deck  896 23 lug 15.52 appmanifest_1088710.acf
-rwxr-xr-x 1 deck deck  699 19 lug 11.52 appmanifest_11020.acf
-rwxr-xr-x 1 deck deck  699 19 lug 11.52 appmanifest_11020.acf
-rwxr-xr-x 1 deck deck  699 19 lug 11.52 appmanifest_11020.acf
-rwxr-xr-x 1 deck deck  699 19 lug 11.52 appmanifest_11020.acf
-rwxr-xr-x 1 deck deck  699 19 lug 11.52 appmanifest_11020.acf
-rwxr-xr-x 1 deck deck  699 19 lug 11.52 appmanifest_11020.acf
-rwxr-xr-x 1 deck deck  699 19 lug 11.52 appmanifest_11020.acf
-rwxr-xr-x 1 deck deck  655 19 lug 11.52 appmanifest_1139900.acf
-rwxr-xr-x 1 deck deck  764 19 lug 11.51 appmanifest_12130.acf
-rwxr-xr-x 1 deck deck  764 22 lug 09.45 appmanifest_1238080.acf
-rwxr-xr-x 1 deck deck  704 10 nov  2022 appmanifest_1391110.acf
-rwxr-xr-x 1 deck deck  602 21 lug 11.03 appmanifest_1455840.acf
-rwxr-xr-x 1 deck deck  672 23 mag 07.55 appmanifest_1580130.acf
-rwxr-xr-x 1 deck deck  694  7 giu 07.25 appmanifest_1628350.acf
-rwxr-xr-x 1 deck deck  589 21 lug 11.03 appmanifest_1659040.acf
-rwxr-xr-x 1 deck deck  618 23 lug 11.56 appmanifest_1869590.acf
-rwxr-xr-x 1 deck deck  746  8 lug 09.03 appmanifest_20828.acf
-rwxr-xr-x 1 deck deck  682  7 lug 08.55 appmanifest_218740.acf
-rwxr-xr-x 1 deck deck  858 23 lug 18.14 appmanifest_225640.acf
-rwxr-xr-x 1 deck deck  780 19 lug 11.52 appmanifest_228760.acf
-rwxr-xr-x 1 deck deck  784 19 lug 11.52 appmanifest_232910.acf
-rwxr-xr-x 1 deck deck  784 19 lug 11.52 appmanifest_232910.acf
-rwxr-xr-x 1 deck deck  780 19 lug 11.52 appmanifest_243360.acf
-rwxr-xr-x 1 deck deck  687 21 lug 11.03 appmanifest_247430.acf
-rwxr-xr-x 1 deck deck 1,3K 21 lug 17.56 appmanifest_250900.acf
-rwxr-xr-x 1 deck deck  814 24 giu 07.30 appmanifest_310790.acf
-rwxr-xr-x 1 deck deck  572 14 lug 08.08 appmanifest_316790.acf
-rwxr-xr-x 1 deck deck  750 14 lug 08.18 appmanifest_323130.acf
-rwxr-xr-x 1 deck deck  788 12 lug 07.17 appmanifest_323180.acf
-rwxr-xr-x 1 deck deck  755 14 lug 17.14 appmanifest_366250.acf
-rwxr-xr-x 1 deck deck  720 24 dic  2022 appmanifest_370900.acf
-rwxr-xr-x 1 deck deck  528 23 lug 18.14 appmanifest_383270.acf
-rwxr-xr-x 1 deck deck  893 22 lug 09.45 appmanifest_40990.acf
-rwxr-xr-x 1 deck deck  893 22 lug 09.45 appmanifest_40990.acf
-rwxr-xr-x 1 deck deck  893 22 lug 09.45 appmanifest_40990.acf
-rwxr-xr-x 1 deck deck  893 22 lug 09.45 appmanifest_40990.acf
-rwxr-xr-x 1 deck deck  532  7 lug 08.55 appmanifest_433550.acf
-rwxr-xr-x 1 deck deck  860  3 giu 09.02 appmanifest_449960.acf
-rwxr-xr-x 1 deck deck  552 11 giu 08.47 appmanifest_456670.acf
-rwxr-xr-x 1 deck deck  813 13 lug 08.16 appmanifest_459280.acf
-????????? ? ?    ?       ?            ? appmanifest_466560.acf
-rwxr-xr-x 1 deck deck  760 19 lug 11.52 appmanifest_544330.acf
-rwxr-xr-x 1 deck deck  777 23 lug 18.14 appmanifest_548430.acf
-rwxr-xr-x 1 deck deck  538 14 lug 08.06 appmanifest_572890.acf
-rwxr-xr-x 1 deck deck  545 23 lug 18.14 appmanifest_588650.acf
-rwxr-xr-x 1 deck deck  545 23 lug 18.14 appmanifest_588650.acf
-rwxr-xr-x 1 deck deck  545 17 lug 08.21 appmanifest_602960.acf
-rwxr-xr-x 1 deck deck  876 23 lug 13.03 appmanifest_631510.acf
-rwxr-xr-x 1 deck deck  876 23 lug 13.03 appmanifest_631510.acf
-rwxr-xr-x 1 deck deck  748 23 lug 18.14 appmanifest_632470.acf
-rwxr-xr-x 1 deck deck  955  8 lug 09.04 appmanifest_677120.acf
-rwxr-xr-x 1 deck deck  565 14 lug 08.07 appmanifest_6850.acf
-rwxr-xr-x 1 deck deck  711 20 lug 22.37 appmanifest_6860.acf
-rwxr-xr-x 1 deck deck  554 23 lug 18.14 appmanifest_6900.acf
-rwxr-xr-x 1 deck deck  553 15 lug 15.45 appmanifest_774801.acf
-rwxr-xr-x 1 deck deck  690 14 lug 08.15 appmanifest_844260.acf
-rwxr-xr-x 1 deck deck  880 18 lug 22.39 appmanifest_846030.acf
-rwxr-xr-x 1 deck deck  699 19 lug 11.52 appmanifest_873940.acf
-rwxr-xr-x 1 deck deck  786 23 lug 18.14 appmanifest_927380.acf
-rwxr-xr-x 1 deck deck  535  7 lug 08.57 appmanifest_956030.acf
drwxr-xr-x 1 deck deck 1,7K 21 lug 10.35 common
drwxr-xr-x 1 deck deck   26  5 giu 19.04 compatdata
drwxr-xr-x 1 deck deck    0 17 lug 18.57 downloading
drwxr-xr-x 1 deck deck  254 23 mag 07.54 music
drwxr-xr-x 1 deck deck   12 21 lug 10.35 temp
drwxr-xr-x 1 deck deck  978 23 lug 18.13 workshop
```
Yeah, seems to be a BtrFS filesystem corruption issue, trying to repair it right now. It's not a protontricks related issue. Closing it.

Thanks for taking a look at it :P
