### ISSUE TITLE
Proton Tricks crashes upon opening flatpak

### ISSUE THREAD

**Issue by Default-XD** [Matoking/protontricks#253]
Protontricks crashes upon opening

Reproduce:
Open the Protontricks flatpak

I am on a Steam Deck

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 241, in main
    steam_apps = get_steam_apps(
                 ^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 1253, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 190, in from_appmanifest
    content = path.read_text(encoding="utf-8")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 117] Structure needs cleaning: '/run/media/mmcblk0p1/steamapps/appmanifest_400.acf'

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Multiple compatdata directories found for app 1887720
Multiple compatdata directories found for app 508440
Multiple compatdata directories found for app 397950
Multiple compatdata directories found for app 1887720
Multiple compatdata directories found for app 960090

**Comment by Matoking** [comment]
"Structure needs cleaning" indicates this could be an issue with file system corruption in your SD card. Could you try reading the instructions detailed in this comment?

https://github.com/Matoking/protontricks/issues/167#issuecomment-1244011276

**Comment by Matoking** [comment]
Closing old issue.
