### ISSUE TITLE
Protontricks doesn't open without giving me this error

### ISSUE THREAD

**Issue by Guilherme-html** [Matoking/protontricks#265]
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 241, in main
    steam_apps = get_steam_apps(
                 ^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 1268, in get_steam_apps
    steam_apps += get_custom_compat_tool_installations(steam_root=steam_root)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 1028, in get_custom_compat_tool_installations
    for tool_app in get_custom_compat_tool_installations_in_dir(dir_):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 973, in get_custom_compat_tool_installations_in_dir
    compat_tools = compat_tools["compatibilitytools"]
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'compatibilitytools'

The only thing I can think of is that it mentions /app/... that don't exist in my system
I'm running chimeraos unstable

**Comment by Guilherme-html** [comment]
WINETRICKS environment variable is not available. Searching from $PATH

it also had this, i forgot to include

**Comment by Matoking** [comment]
Do you have any custom compatibility tools installed besides the stock Proton? If so, what exactly? They should be found as directories inside both `~/.steam/steam/compatibilitytools.d/` and `/usr/share/steam/compatibilitytools.d/`.

Protontricks is trying to parse the `compatibilitytool.vdf` file inside each directory and is crashing due to the missing `compatibilitytools`. That seems weird, since each compatibility tool should declare that field as far as I know.

**Comment by Guilherme-html** [comment]
> Do you have any custom compatibility tools installed besides the stock Proton? If so, what exactly? They should be found as directories inside both `~/.steam/steam/compatibilitytools.d/` and `/usr/share/steam/compatibilitytools.d/`.
> 
> Protontricks is trying to parse the `compatibilitytool.vdf` file inside each directory and is crashing due to the missing `compatibilitytools`. That seems weird, since each compatibility tool should declare that field as far as I know.


There isn't a compatibilitytool.vdf file inside them, is that the problem then?

**Comment by Matoking** [comment]
Is there a `compatibilitytool.vdf` file in `~/.steam/steam/compatibilitytools.d`? If so, what are its contents?

**Comment by Guilherme-html** [comment]
> Is there a `compatibilitytool.vdf` file in `~/.steam/steam/compatibilitytools.d`? If so, what are its contents?

There isn't a `compatibilitytool.vdf`
Sorry for the late response

**Comment by Matoking** [comment]
Closing old issue, please open a new issue if this problem still exists.
