### ISSUE TITLE
Unable to open game data, "invalid magic number"

### ISSUE THREAD

**Issue by DisciplesOfChaos** [Matoking/protontricks#271]
**Describe the bug**
I launch the GUI, and then click the game I want to modify (trying to get this to work)
https://github.com/DrapNard/InfiniteFusion-Launcher

**To Reproduce**
`protontricks --gui`
click game

**Expected behavior**
let me do things

**System (please complete the following information):**
 - Distro: Ubuntu 22.04.3
 - Protontricks installation method: apt, and flatpack
 - Steam version: Stable

**Additional context**
```
$ protontricks --gui -v
protontricks (INFO): Found Steam directory at /home/okphin/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/okphin/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (WARNING): Steam library folder /media/okphin/Steamlib/SteamLibrary not found. Protontricks might not have access to the directory.
protontricks (INFO): Currently logged-in Steam user: wardoc999
protontricks (INFO): Found 2 Steam shortcuts running using Steam compatibility tools
protontricks (INFO): Using 'zenity' as GUI provider
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 214, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
```

**Comment by Matoking** [comment]
Protontricks 1.7.0 is old and doesn't support the newer Steam client. If you've installed Protontricks via APT, try uninstalling it and using another installation method instead (eg. Flatpak).

**Comment by iThorgrim** [comment]
I have the "same" error via FlatPak :

```bash
protontricks (INFO): Found Steam directory at /home/ithorgrim/.local/share/Steam
protontricks (INFO): Using default Steam Runtime at /home/ithorgrim/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: w_halumeth
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Using 'zenity' as GUI provider
Traceback (most recent call last):
  File "/home/ithorgrim/.local/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/ithorgrim/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/home/ithorgrim/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ithorgrim/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/cli/main.py", line 274, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/home/ithorgrim/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/steam.py", line 821, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ithorgrim/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/steam.py", line 610, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/home/ithorgrim/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/steam.py", line 540, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
```

OS : Debian 12
Steam installed via FlatPak

**Comment by Matoking** [comment]
Closing old issue.
