### ISSUE TITLE
Crashes while open the application

### ISSUE THREAD

**Issue by llGenesis** [Matoking/protontricks#272]
**Describe the bug**
Crashes while open the application

**To Reproduce**
Opening it 

**System (please complete the following information):**
 - Distro: Arch Linux/ Dual Bootable to Windows 10
 - Protontricks installation method: Flatpak, 
 - Protontricks version:  1.11.0
 - Steam version: 1702079146

**Additional context**
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 244, in main
    steam_apps = get_steam_apps(
                 ^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 1313, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 201, in from_appmanifest
    content = path.read_text(encoding="utf-8")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error: '/run/media/ja/Mehr-Games/Steam/steamapps/appmanifest_480.acf'

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.15.6.
Found Steam directory at /home/ja/.local/share/Steam
Using default Steam Runtime at /home/ja/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 10 Steam library folders
Steam library folder /run/media/ja/Programme und Games/Steam not found. Protontricks might not have access to the directory.
Steam library folder /run/media/ja/Programme und Games/Windows Games/Steam not found. Protontricks might not have access to the directory.
Steam library folder /mnt/Windows Games/Steam not found. Protontricks might not have access to the directory.
=============

the Folder Programme und Games does not exists anymore i renamed it to "Games" the path is /run/media/ja/Games/Windows_Games/Steam/ there is also the windows install location of steam
To my knowledge there shoud be only 4 Steam library folders not 10
the command flatpak override --user --filesystem=/run/media/ja/Games/Windows_Games/Steam com.github.Matoking.protontricks
was executed

**Comment by llGenesis** [comment]
fixed with repairing the llibrary inside windows
