### ISSUE TITLE
Protontricks will not work

### ISSUE THREAD

**Issue by xDieymirx** [Matoking/protontricks#274]
**Bug**

Cannot use Protontricks, because when I select a game, it crashes with this log.

**Steps to reproduce the behavior**

1. Open protontricks
2. select a game.

**Expectation**

Expected to be able to download dll's for Skyrim SE to use for nemesis and mo2

**System**
 - Distro: [EndeavourOS]
 - Protontricks installation method: [Community Package, AUR]
 - Protontricks version: run 1.11.0
 - Steam version: non-beta 

**Log**

protontricks (INFO): Found Steam directory at /home/sean/.local/share/Steam
protontricks (INFO): Using default Steam Runtime at /home/sean/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (INFO): Currently logged-in Steam user: sikeday
protontricks (INFO): Found 0 Steam shortcuts running using Steam compatibility tools
protontricks (INFO): Using 'yad' as GUI provider
protontricks (INFO): User has configured app Proton version (CompatToolMapping): proton_8
protontricks (INFO): User has configured default Proton version (CompatToolMapping): proton_experimental
protontricks (INFO): Found active compatibility tool: Proton 8.0
protontricks (INFO): Active compatibility tool is a Proton installation
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/cli/main.py", line 283, in main
    run_command(
  File "/usr/lib/python3.11/site-packages/protontricks/util.py", line 375, in run_command
    str(proton_app.proton_dist_path / "lib64" / "wine"),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'

**Comment by Matoking** [comment]
The Proton installation seems to be incomplete. Have you started Skyrim SE through Steam at least once?

If not, could you check the Proton installation contents for Proton 8.0? Find Proton 8.0 in your Steam library (ensure tools are shown), right-click the entry in the library -> Properties -> Installed Files -> Browse...

The directory should contain a `proton` file as well as a `dist` directory.

**Comment by xDieymirx** [comment]
> well

it has those files, i opened up skyrim SE now, using proton experimental. I get a different error now, being:

![image](https://github.com/Matoking/protontricks/assets/129011037/915834d5-b2f2-4487-9a8f-e912aed99ff3)

and the console log is 

**Log**

protontricks --gui
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.545.29.06 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH (unset), ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
winetricks GUI enabled, using kdialog 23.08.4

**Comment by Matoking** [comment]
I pushed a small fix to master. Protontricks has an error message prompting the user to launch the game first on Steam if the Proton installation is incomplete; this wasn't shown properly for Protontricks GUI, however.

---

The "Unknown file arch: 65" error is caused by a different issue related to Winetricks and can be ignored if Protontricks otherwise works. In short, Winetricks tries to examine the `wine` and `wineserver` executables to see if they're 64-bit or 32-bit binaries; this fails because Protontricks creates shell scripts instead which call the underlying binaries. This will likely have to be fixed in the Winetricks side of things, though I haven't found a solution yet.

If you ignore the error messages (you might have to click OK a few times), does Proton Experimental work OK? How about Proton 8.0?

**Comment by xDieymirx** [comment]
> I pushed a small fix to master. Protontricks has an error message prompting the user to launch the game first on Steam if the Proton installation is incomplete; this wasn't shown properly for Protontricks GUI, however.
> 
> The "Unknown file arch: 65" error is caused by a different issue related to Winetricks and can be ignored if Protontricks otherwise works. In short, Winetricks tries to examine the `wine` and `wineserver` executables to see if they're 64-bit or 32-bit binaries; this fails because Protontricks creates shell scripts instead which call the underlying binaries. This will likely have to be fixed in the Winetricks side of things, though I haven't found a solution yet.
> 
> If you ignore the error messages (you might have to click OK a few times), does Proton Experimental work OK? How about Proton 8.0?

I can use proton experimental and Proton 8, however I cannot get protontricks to run, and will only use winetricks.

**Comment by erkinalp** [comment]
Same issue.
