### ISSUE TITLE
Error selecting a game

### ISSUE THREAD

**Issue by Skulp55** [Matoking/protontricks#312]
**Describe the bug**
The bug doesn't let you modify any settings for the desired game.

**To Reproduce**
1. Run command `protontricks --gui`
2. select any game

**Expected behavior**
Selecting the game should then boot up protontricks for the desired game.

**System (please complete the following information):**
 - Distro: Linux Mint 21.3 x86_64
 - Protontricks installation method: Apt and flatpak (it gives the same error on both)
 - Protontricks version: protontricks (1.11.1)
 - Steam version: Steam Families Beta

**Additional context**

Traceback (most recent call last):
  File "/home/skulp/.local/bin/protontricks", line 8, in <module>
    sys.exit(cli())
  File "/home/skulp/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/home/skulp/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/home/skulp/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
  File "/home/skulp/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/home/skulp/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
  File "/home/skulp/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
  File "/home/skulp/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

**Comment by Skulp55** [comment]
ok i fixed it, just don't use any of the beta
