### ISSUE TITLE
crash upon selecting a game 

### ISSUE THREAD

**Issue by github2452** [Matoking/protontricks#314]
**Describe the bug**
crash due to  a nonexisting directory or I don't know. 

**To Reproduce**
Selecting a game in the gui or running any command with a game for example: "protontricks 123 xna40"

**Expected behavior**
With the GUI version a new Window. with the cli version executing the  expected commands

**System (please complete the following information):**
 - Distro: Ubuntu 24.04 LTS
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.11.1
 - Steam version: 1718904662

**Additional context**

**If the error happens when trying to run a Protontricks command, run the command again using the `-vv` flag and copy the output!**

_protontricks 855860 xna40 -vw_

pressure-vessel-wrap[9]: E: linkat: No such file or directory
Traceback (most recent call last):
  File "/app/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 370, in main
    returncode = run_command(
                 ^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/util.py", line 516, in run_command
    raise RuntimeError(
RuntimeError: bwrap launcher crashed, returncode: 1

the log from the gui: 
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 290, in main
    run_command(
  File "/app/lib/python3.11/site-packages/protontricks/util.py", line 516, in run_command
    raise RuntimeError(
RuntimeError: bwrap launcher crashed, returncode: 1

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.14.6.
Found Steam directory at /home/thememe/.local/share/Steam
Using default Steam Runtime at /home/thememe/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: josephss242
Couldn't find custom shortcuts. Maybe none have been created yet?
Using 'yad' as GUI provider
User has configured app Proton version (CompatToolMapping): proton_9
Found active compatibility tool: Proton 9.0
Active compatibility tool is a Proton installation
Using 'bwrap = True' as default value
Using separately installed Steam Runtime: Steam Linux Runtime 3.0 (sniper)
Running Steam Runtime using bwrap containerization.
If any problems arise, please try running the command again using the `--no-bwrap` flag and make an issue report if the problem only occurs when bwrap is in use.
Created Steam Runtime Wine binary directory at /home/thememe/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 9.0/bin
WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
Starting bwrap launcher process: /home/thememe/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 9.0/bin/bwrap-launcher
Terminating launcher process 14
Launcher process terminated

**Comment by dslauter** [comment]
Same issue on Linux Mint 22

**Comment by Osced86** [comment]
Same issues for me as well I'm on Ubuntu 24.04 with latest protontricks version 1.11.1 via pipx installation.

**Comment by Osced86** [comment]
I seems to have got around the problem, by installing winetricks manually, see link for how to manually install it: https://github.com/Winetricks/winetricks?tab=readme-ov-file#manual-install and then using --no-bwrap flag.  Still get some errors/warning but are able to do what I want to do.

**Comment by vproper** [comment]
Same error on Arch Linux

**Comment by stevenlafl** [comment]
@Matoking 

> Could someone who's affected try running `journalctl -f` in one window, and then run Protontricks in another window while the first window is still open? If the security policy is to blame, I'm guessing a few lines prefixed `audit: ` and containing the segment `apparmor="DENIED"` should pop up.

Without --no-bwrap:

```
Jul 31 16:36:38 DESKTOP-1VF8NE6 kernel: audit: type=1400 audit(1722465398.482:281): apparmor="AUDIT" operation="userns_create" class="namespace" info="Userns create - transitioning profile" profile="unconfined" pid=26536 comm="srt-bwrap" requested="userns_create" target="unprivileged_userns"
Jul 31 16:36:38 DESKTOP-1VF8NE6 kernel: audit: type=1400 audit(1722465398.482:282): apparmor="DENIED" operation="open" class="file" info="Failed name lookup - disconnected path" error=-13 profile="unprivileged_userns" name="proc/26537/uid_map" pid=26537 comm="srt-bwrap" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
Jul 31 16:36:38 DESKTOP-1VF8NE6 kernel: audit: type=1400 audit(1722465398.484:283): apparmor="AUDIT" operation="userns_create" class="namespace" info="Userns create - transitioning profile" profile="unconfined" pid=26538 comm="bwrap" requested="userns_create" target="unprivileged_userns"
Jul 31 16:36:38 DESKTOP-1VF8NE6 kernel: audit: type=1400 audit(1722465398.484:284): apparmor="DENIED" operation="open" class="file" info="Failed name lookup - disconnected path" error=-13 profile="unprivileged_userns" name="proc/26539/uid_map" pid=26539 comm="bwrap" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
Jul 31 16:36:38 DESKTOP-1VF8NE6 kernel: audit: type=1400 audit(1722465398.486:285): apparmor="AUDIT" operation="userns_create" class="namespace" info="Userns create - transitioning profile" profile="unconfined" pid=26541 comm="srt-bwrap" requested="userns_create" target="unprivileged_userns"
Jul 31 16:36:38 DESKTOP-1VF8NE6 kernel: audit: type=1400 audit(1722465398.486:286): apparmor="DENIED" operation="capable" class="cap" profile="unprivileged_userns" pid=26542 comm="srt-bwrap" capability=8  capname="setpcap"
Jul 31 16:36:38 DESKTOP-1VF8NE6 kernel: audit: type=1400 audit(1722465398.486:287): apparmor="DENIED" operation="open" class="file" info="Failed name lookup - disconnected path" error=-13 profile="unprivileged_userns" name="proc/26542/uid_map" pid=26542 comm="srt-bwrap" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
```

with --no-bwrap, I don't get journal entries. However, I do get:

```
Executing cd /usr/bin
------------------------------------------------------
warning: Unknown file arch of /home/stevenlafl/.cache/protontricks/proton/Proton 9.0/bin/wineserver.
------------------------------------------------------
protontricks (INFO): Command returned 1
```


This is using the latest pipx install for winetricks. It doesn't seem to matter _at all_ what Proton version is selected. I can, in fact, launch games -- so the "file arch" problem is not related to whether or not Wine/Proton is actually working.

**Comment by dotaxis** [comment]
Having this issue on a steam deck where winetricks is not an option :/

**Comment by Matoking** [comment]
> Having this issue on a steam deck where winetricks is not an option :/

What error message are you getting specifically? This error in particular is identified by the "bwrap launcher crashed, returncode: 1".

The "Invalid file magic number" error which affects all Steam beta users is in #304, with a workaround described in the same issue.
