### ISSUE TITLE
trying too use pizza tower and 

### ISSUE THREAD

**Issue by Qwerty1235678** [Matoking/protontricks#332]
**Describe the bug**
this is the error i got 
"Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 604, in find_steam_compat_tool_app
    content = config_vdf_path.read_text()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 43226: invalid start byte"

**To Reproduce**
1. Run command `protontricks foo bar`
2. Command fails and error is displayed

**Expected behavior**
I expected too be able too do what you normally can do with proton tricks

**System (please complete the following information):**
 - Distro: zorin 0s 17.1
 - Protontricks installation method: flatpak
 - Protontricks version: 1.14.6.
 - Steam version: not running the beta participation 

**Additional context**
following a tutorial i found on reddit too install the pizza oven mod loader and it all requires proton tricks.
(i have winetricks installed as well as all prerequisites)

**Comment by Qwerty1235678** [comment]
.........................

**Comment by Matoking** [comment]
Could you try installing the beta version using the instructions described here?

https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470

Also, please report back if this fixes the issue.
