### ISSUE TITLE
Protontricks Runtime Error: Protontricks crashes, no matter what game I choose.

### ISSUE THREAD

**Issue by StrawberryES** [Matoking/protontricks#335]
**Describe the bug**
Protontricks crashes, no matter what game I choose. I've launched all games that I tested at least once, no matter what Protontricks always has a runtime error. I've tested games that are installed in my home directory and games that are installed on my internal SSD's. 

**To Reproduce**
Selecting any game from the gui

**Expected behavior**
A new window should open and the prefix should be configurable. 

**System (please complete the following information):**
 - Distro: openSUSE Tumbleweed 20240829 x86_64
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.11.1
 - Steam version: 1721173382

**Additional context**

**If the error happens when trying to run a Protontricks command, run the command again using the `-vv` flag and copy the output!**

**Output via terminal:**

https://gist.github.com/StrawberryES/01c67cfd70449549478df8e0d66651df

**Output via Yad:** 

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 290, in main
    run_command(
  File "/app/lib/python3.11/site-packages/protontricks/util.py", line 355, in run_command
    raise RuntimeError(
RuntimeError: Proton Experimental is missing the required Steam Runtime. You may need to launch a Steam app using this Proton version to finish the installation.

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.15.10.
Found Steam directory at /home/even/.local/share/Steam
Using default Steam Runtime at /home/even/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 4 Steam library folders
Steam library folder /home/even/Laufwerke/SSD_02/SteamLibrary not found. Protontricks might not have access to the directory.
Currently logged-in Steam user: lalamann2
Shortcut Battle.net-Setup.exe (2976730483) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Rockstar-Games-Launcher.exe (3496476047) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut UbisoftConnectInstaller.exe (3407698558) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut EAappInstaller.exe (4022837057) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
User has configured app Proton version (CompatToolMapping): proton_experimental
User has configured default Proton version (CompatToolMapping): proton_9
Found active compatibility tool: Proton Experimental
Active compatibility tool is a Proton installation

**Comment by StrawberryES** [comment]
Never mind, the libraryfolders.vdf in my home directory had an old path to one of my SSD's. I updated the Path now it's working again.
