### ISSUE TITLE
The appinfo.vdf version might not be supported by the current version of Protontricks

### ISSUE THREAD

**Issue by ademarest** [Matoking/protontricks#340]
Steam released a new build today.
When attempting to select any steam app protontricks complains about appinfo.vdf and crashes.
This happens on Fedora 40 and Archlinux.
Here's my Steam about section. It is a stable build.
![image](https://github.com/user-attachments/assets/58df4487-b77e-4671-95c6-f9ee6157a519)

Terminal output regarding the syntax error:
``` bash
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 297, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 860, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 621, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 543, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
```

**Comment by Heisenborgar** [comment]
I got the same errors. Literally can't run apps under protontricks anymore

**Comment by d3-X-t3r** [comment]
@ademarest @Heisenborgar The workaround/fix here worked for me: https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470

**Comment by Matoking** [comment]
As stated, the beta version of Protontricks has to be installed per the [instructions](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470). There's also a notice in the header of the README.
