### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 

### ISSUE THREAD

**Issue by Combine-sudo** [Matoking/protontricks#342]
Traceback (most recent call last):
  File "/home/Denis/.local/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/Denis/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/home/Denis/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Denis/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/cli/main.py", line 293, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/home/Denis/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/steam.py", line 904, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Denis/.local/share/pipx/venvs/protontricks/lib/python3.12/site-packages/protontricks/steam.py", line 660, in find_steam_compat_tool_app
    content = config_vdf_path.read_text()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1028, in read_text
    return f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 29908: invalid continuation byte

**System**
 - Distro: Arch Linux 6.10.9-arch-1
 - Protontricks installation method: pipx
 - Protontricks version: protontricks (1.11.2.dev8+gf7b1fa3)
 - Steam version: steam beta update

**Additional context**

tried to uninstall and reinstall via git,AUR,flathub and pipx multiple times but still got the same issue.

**Comment by orkel1215** [comment]
I have the same problem.

- Distro: EndevourOS (Linux 6.10.10-zen1-1-zen)
- Protontricks installation method: AUR (yay)
- Protontricks version: 1.11.1-2
- Steam version: steam beta update

**Comment by orkel1215** [comment]
fixed for me in the new update.
