### ISSUE TITLE
ProtonTricks crashes after picking a prefix

### ISSUE THREAD

**Issue by CherriCola** [Matoking/protontricks#350]
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Found 39 Steam shortcuts running using Steam compatibility tools

**Comment by DockterTeagle** [comment]
I have a similair issue as well mine is:
```bash
Traceback (most recent call last):
  File "/nix/store/39pyz3w5qxcr4w0rs8rcvxgd9wi9svlj-protontricks-1.11.1/bin/.protontricks-wrapped", line 9, in <module>
    sys.exit(cli())
             ^^^^^
  File "/nix/store/39pyz3w5qxcr4w0rs8rcvxgd9wi9svlj-protontricks-1.11.1/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/nix/store/39pyz3w5qxcr4w0rs8rcvxgd9wi9svlj-protontricks-1.11.1/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/39pyz3w5qxcr4w0rs8rcvxgd9wi9svlj-protontricks-1.11.1/lib/python3.12/site-packages
/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/nix/store/39pyz3w5qxcr4w0rs8rcvxgd9wi9svlj-protontricks-1.11.1/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/39pyz3w5qxcr4w0rs8rcvxgd9wi9svlj-protontricks-1.11.1/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/nix/store/39pyz3w5qxcr4w0rs8rcvxgd9wi9svlj-protontricks-1.11.1/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
    ```

**Comment by DockterTeagle** [comment]
after updating to the latest version I no longer have this issue
