### ISSUE TITLE
protontricks gui won't start

### ISSUE THREAD

**Issue by esanscoopsers** [Matoking/protontricks#351]
tried protontricks from aur and protontricks-git from aur. tried from pipx. happens with winetricks as well.

I get this error

~~~
[ethan@arch ~]$ protontricks 489830 --gui
pressure-vessel-wrap[36378]: W: Not sharing path --filesystem="/etc" with container because "/etc" is reserved by the container framework
pressure-vessel-wrap[36378]: W: Not sharing path --filesystem="/sbin" with container because "/sbin" is reserved by the container framework
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale en_CA.UTF-8...
pressure-vessel-locale-gen: Generated locale en_CA.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[36440]: W: Container startup will be faster if missing locales are created at OS level
winetricks GUI enabled, using zenity 4.0.2

(zenity:36622): Gtk-WARNING **: 17:03:22.325: Unknown key gtk-modules in /home/ethan/.config/gtk-4.0/settings.ini

(zenity:36622): Adwaita-WARNING **: 17:03:22.376: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Gdk-Message: 17:03:22.456: Error 71 (Protocol error) dispatching to Wayland display.

(zenity:36656): Gtk-WARNING **: 17:03:22.487: Unknown key gtk-modules in /home/ethan/.config/gtk-4.0/settings.ini

(zenity:36656): Adwaita-WARNING **: 17:03:22.539: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Gdk-Message: 17:03:22.618: Error 71 (Protocol error) dispatching to Wayland display.
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------

(zenity:37233): Gtk-WARNING **: 17:03:26.945: Unknown key gtk-modules in /home/ethan/.config/gtk-4.0/settings.ini

(zenity:37233): Adwaita-WARNING **: 17:03:26.996: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Gdk-Message: 17:03:27.075: Error 71 (Protocol error) dispatching to Wayland display.
------------------------------------------------------
warning: You apppear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------

(zenity:37261): Gtk-WARNING **: 17:03:27.102: Unknown key gtk-modules in /home/ethan/.config/gtk-4.0/settings.ini

(zenity:37261): Adwaita-WARNING **: 17:03:27.155: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Gdk-Message: 17:03:27.234: Error 71 (Protocol error) dispatching to Wayland display.
Using winetricks 20240105 - sha256sum: 8f28985b06e9e04b5268e2aef3429b2a0f6abd4fd12c4a30472dfe66355128fa with wine-8.0 and WINEARCH=win64

(zenity:37903): Gtk-WARNING **: 17:03:29.117: Unknown key gtk-modules in /home/ethan/.config/gtk-4.0/settings.ini

(zenity:37903): Adwaita-WARNING **: 17:03:29.168: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Gdk-Message: 17:03:29.254: Error 71 (Protocol error) dispatching to Wayland display.
~~~

**Comment by Matoking** [comment]
The `Error 71 (Protocol error) dispatching to Wayland display` error makes me suspect something is wrong with the desktop environment. Are any dialogs showing up at all? What desktop environment are you using?

Also, if your desktop environment still supports X11, you could try logging out, selecting the X11 session, logging back in and checking if that works.

For what it's worth, KDE Plasma 6 with Wayland has worked fine on Arch on my end.

**Comment by AZCurt** [comment]
Having the same problem in Gentoo and Arch, KDE Wayland. Switched my Gentoo back to X11 and have the following error with protontricks (1.10.5).

```
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 274, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 821, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 610, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 540, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
```
Winetricks under X11

```
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You apppear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
Using winetricks 20240105 - sha256sum: 8f28985b06e9e04b5268e2aef3429b2a0f6abd4fd12c4a30472dfe66355128fa with wine-9.14 (Staging) and WINEARCH=win64
winetricks GUI enabled, using kdialog 24.05.2
x:  100   y:  100   w:  600   h:  400
x:  100   y:  100   w:  600   h:  400
kf.kio.gui: Failed to determine systemd version, falling back to extremely legacy forking mode.
x:  100   y:  100   w:  600   h:  400
x:  100   y:  100   w:  600   h:  400
```
I have a Solus XFCE build and can try it there as well.

**Comment by Matoking** [comment]
1.12.0 fixes the "Invalid file magic number" error and is required for newer versions of Steam.

Googling suggests there are multiple causes that might cause that error, and it might be related to the GUI framework that this GNOME app (zenity) uses. See [here](https://discussion.fedoraproject.org/t/gdk-message-error-71-protocol-error-dispatching-to-wayland-display/127927) for an example. Are you using the NVIDIA drivers by any chance?

To test this, you could try the following stand-alone command, which should display a dialog with the text "This is a test".

```sh
$ zenity --info --text="This is a test"
``` 

If that doesn't work, what if you prefix it with `GSK_RENDERER=gl` like so?

```sh
$ GSK_RENDERER=gl zenity --info --text="This is a test"
```

**Comment by AZCurt** [comment]
As Gentoo is my primary I decided to use the dreaded ~amd64 keyword. :) Updated protontricks by setting the following in package_accept_keywords to install 1.12.0 , which took care of the problem.

>=app-emulation/protontricks-1.12.0 ~amd64
>=dev-python/vdf-3.4_p20240630::gentoo ~amd64

Arch is secondary and not a high priority. Arch has 1.12.0 installed, but no joy. Running  GSK_RENDERER=gl zenity --info --text="This is a test" works as intended with the following errors.

```
(zenity:3862): Gtk-WARNING **: 09:34:06.574: Unknown key gtk-modules in /home/curt/.config/gtk-4.0/settings.ini

(zenity:3862): Adwaita-WARNING **: 09:34:06.604: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(zenity:3862): Gdk-WARNING **: 09:34:20.810: ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (30) not an integer multiple of theme size (24)
```
I get similar errors with X11, so I need to track down other potential problems with rendering. Will try the workaround listed in the link! (not sure how I missed it)

Thanks for the reply.

**Comment by Matoking** [comment]
The warnings are harmless if the application works correctly (I get a _lot_ of those "Please use X instead" warnings regardless of the GTK apps I use, and I get the hunch they're intended more for developers than users), while `Error 71 (Protocol error) dispatching to Wayland display` seemed to indicate complete failure for the application to work.

Assuming your Arch installation is hitting the Wayland error, `GSK_RENDERER=gl protontricks ...` should act as a workaround.
