### ISSUE TITLE
"Protontricks was closed due to the following error" (Ubuntu 24.10)

### ISSUE THREAD

**Issue by dziadulewicz** [Matoking/protontricks#358]
**Describe the bug**

Error dialog after crash:

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 610, in find_steam_compat_tool_app
    section for section in iter_appinfo_sections(appinfo_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/tux/.local/share/Steam
Using default Steam Runtime at /home/tux/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Currently logged-in Steam user: 
Couldn't find custom shortcuts. Maybe none have been created yet?
Using 'zenity' as GUI provider

**To Reproduce**
1. Install Protontricks from the App Center and start Protontricks 
2. Choose a game to work with ("Select Steam app")and click Ok 
3. Crash. And the before stated error dialog appears

**Comment by dziadulewicz** [comment]
Found 2 Steam library folders: this is a laptop with an SSD and an external older HDD (which holds all the games downloaded). If this makes Protontricks mechanism possibly confused (?)

**Comment by Matoking** [comment]
Are you using Protontricks v1.12.0? Older releases are no longer compatible with the current Steam client.

**Comment by YolKay** [comment]
> Are you using Protontricks v1.12.0? Older releases are no longer compatible with the current Steam client.

I'm also having this same issue. I'm running Ubuntu and have the 1.12.0 version of the flatpack installed. I went through [Issue 304](https://github.com/Matoking/protontricks/issues/304), but I haven't found a solution yet.

**Comment by Matoking** [comment]
> > Are you using Protontricks v1.12.0? Older releases are no longer compatible with the current Steam client.
> 
> I'm also having this same issue. I'm running Ubuntu and have the 1.12.0 version of the flatpack installed. I went through [Issue 304](https://github.com/Matoking/protontricks/issues/304), but I haven't found a solution yet.

The Flatpak version of Protontricks was missing default filesystem permissions for the Steam Snap installation directories. An update should go live in a few hours with a fix. Can you check if this solves the issue?

**Comment by Robotic-Actual** [comment]
Still having this issue on Ubuntu 24.04 with the latest version of MO2

**Comment by 0x6A7232** [comment]
MX Linux, based on Debian Bookworm, latest version I can get from the official repos is 1.10.2 and the flatpak version doesn't work (filesystem permissions issue, it seems, even when granted with Flatseal?)
