### ISSUE TITLE
"Protontricks was closed due to the following error"

### ISSUE THREAD

**Issue by brookely42** [Matoking/protontricks#367]
**Describe the bug**
Launches protontricks, allows game selection, then crashes with error upon selecting any game. 

**To Reproduce**
1. Open Protontricks
2. Select game and click OK
3. Protontricks closes with error

**Expected behavior**
To go into a Winetricks-esque menu, so that I can change things in the wine prefix, among other things

**System (please complete the following information):**
 - Distro: Tuxedo OS 3
 - Protontricks installation method: .deb file from Steam website
 - Protontricks version: 1.10.5
 - Steam version: check if you're running Steam beta; not running any beta

**Additional context**
Trying to use Protontricks to follow various mod manager install guides (Reloaded II, SAModManager). Have successfully done process with Reloaded II install on Linux Mint, Fedora, and earlier install of Tuxedo OS 3. 

**Error Message**
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 274, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 821, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 610, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 540, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/brookea/.local/share/Steam
Using default Steam Runtime at /home/brookea/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Currently logged-in Steam user: Steamusername
Couldn't find custom shortcuts. Maybe none have been created yet?
Using 'zenity' as GUI provider

**Comment by Matoking** [comment]
Protontricks 1.10.5 is outdated; you need 1.12.0 as the older versions don't support the latest Steam client.

The easiest option might be to install the Flatpak version instead. You can check the instructions [here](https://github.com/Matoking/protontricks?tab=readme-ov-file#flatpak-recommended).
