### ISSUE TITLE
Protontricks not working on VC_Redist.x64.exe

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Matoking/protontricks#368]
**Describe the bug**
ProtonTricks errors when trying to run it on VC_redistx64.exe

**To Reproduce**
Right click on VC Redist exe and select run with winetricks.
Then asks for what program to run it on (in my case the game was cyberpunk 2077)

**Expected behavior**
I have no idea but to make some 2077 mods work apparently needs this.

**System (please complete the following information):**
 - Distro: Linux Mint 22 Cinnamon
 - Protontricks installation method: Via the Software Manager for Mint
 - Protontricks version: 1.10.5-1
 - Steam version: not in beta

**Additional context**
The entire error output: 

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 329, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 821, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 610, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 540, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/baron/.steam/debian-installation
Found 1 Steam library folders
Currently logged-in Steam user: -----hotmail.com
Couldn't find custom shortcuts. Maybe none have been created yet?
Using 'zenity' as GUI provider
Calling `protontricks` with the command: ['--no-background-wineserver', '--no-term', '-c', "wine '/home/baron/Downloads/VC_redist.x64.exe'", '1091500']
Using default Steam Runtime at /home/baron/.steam/debian-installation/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: -----hotmail.com
Couldn't find custom shortcuts. Maybe none have been created yet?

**Comment by Matoking** [comment]
Protontricks 1.10.5 is outdated; you need 1.12.0 as the older versions don't support the latest Steam client. Ubuntu and related distros usually ship outdated versions of Protontricks.

The easiest option might be to install the Flatpak version instead. You can check the instructions [here](https://github.com/Matoking/protontricks?tab=readme-ov-file#flatpak-recommended).

**Comment by TheBitcoinBaron** [comment]
I got the flatpack version, but how do I run things with it? 

I am trying to VCRedist as above, but having got the protontricks (flatpack) in the start menu.... what then?

Clicking on it and then selecting cyberpunk it will start the game, but i want to install VCRedist into it somehow?
