### ISSUE TITLE
Protontricks was closed due to the following error

### ISSUE THREAD

**Issue by GodsBadAssBlade** [Matoking/protontricks#370]
I tried to get protontricks to make a directory for mod organizer 2 to use skyrim vr, but in all cases failled

simply opening the wanted app in the directory in protontricks was enough to make it consistently fail 

open protontricks, select skyrim vr, protontricks closes with this error message

 - Distro: Pop_OS! 22.04LTS
 - Protontricks installation method: Distros own package handler
 - Protontricks version: protontricks (1.7.0)
 - Steam version: 1733265492

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 214, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/godsbadassblade/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/godsbadassblade/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 4 Steam library folders
Multiple compatdata directories found for app 603850
Multiple compatdata directories found for app 1118200
Multiple compatdata directories found for app 1545450
Multiple compatdata directories found for app 1017180
Multiple compatdata directories found for app 1454400
Multiple compatdata directories found for app 1808120
Multiple compatdata directories found for app 447040
Multiple compatdata directories found for app 1245040
Multiple compatdata directories found for app 961940
Multiple compatdata directories found for app 1113280
Multiple compatdata directories found for app 858280
Multiple compatdata directories found for app 1580130
Multiple compatdata directories found for app 1054830
Multiple compatdata directories found for app 1420170
Multiple compatdata directories found for app 365590
Multiple compatdata directories found for app 704270
Multiple compatdata directories found for app 244850
Currently logged-in Steam user: godsangelblade1
Found 8 Steam shortcuts running using Steam compatibility tools
Using 'zenity' as GUI provider

**Comment by Matoking** [comment]
Protontricks 1.10.5 is outdated; you need 1.12.0 as the older versions don't support the latest Steam client. Ubuntu and the derived distros (such as Pop_OS!) usually ship outdated versions of Protontricks.

The easiest option might be to install the Flatpak version instead. You can check the instructions [here](https://github.com/Matoking/protontricks?tab=readme-ov-file#flatpak-recommended).
