### ISSUE TITLE
Protontricks was closed due to the following error

### ISSUE THREAD

**Issue by JJoeDev** [Matoking/protontricks#372]
protontricks version 1.12.0 from the void linux repo closes after selecting a game from steam that uses proton

**To Reproduce**
1. Run command `protontricks foo bar`
2. Command fails and error is displayed

1. Open protontricks gui
2. Select the game
3. The error gets displayed

The same goes if you try to launch it from the cli using the game id or name. --no-bwrap also does not work

### System
- Distro: Void Linux
- Kernel 6.6.64_1
- Install method: xbps-install -S protontricks
- Protontricks version: 1.12.0
- Steam version: No beta selected

### Error
```
pressure-vessel-wrap[27696]: W: Not sharing path --filesystem="/etc" with container because "/etc" is reserved by the container framework
pressure-vessel-wrap[27696]: W: Not sharing path --filesystem="/lib32" with container because "/lib32" is reserved by the container framework
pressure-vessel-wrap[27696]: W: Not sharing path --filesystem="/sbin" with container because "/sbin" is reserved by the container framework
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale en_DK.UTF-8...
pressure-vessel-locale-gen: Generated locale en_DK.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[27748]: W: Container startup will be faster if missing locales are created at OS level
steam-runtime-launcher-service[27793]: E: Can't find session bus: Failed to execute child process “dbus-launch” (No such file or directory)
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.12.0', 'console_scripts', 'protontricks')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 394, in main
    returncode = run_command(
                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/util.py", line 516, in run_command
    raise RuntimeError(
RuntimeError: bwrap launcher crashed, returncode: 69
```

**Comment by JJoeDev** [comment]
Turns out that the placement of the flags matter. Using --no-bwrap before the game ID fixed all the issues....
