### ISSUE TITLE
Won't open.

### ISSUE THREAD

**Issue by nanashi89** [Matoking/protontricks#377]
**Describe the bug**
App does not open, leaves me with the following message:

"Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 258, in main
    steam_apps = get_steam_apps(
                 ^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 1363, in get_steam_apps
    steamapps_dirs = _get_steamapps_subdirs(path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 308, in _get_steamapps_subdirs
    dirs = list(
           ^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 308, in <genexpr>
    dirs = list(
               ^
  File "/usr/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error: '/run/media/bazzite/DeckBackup'

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.15.10.
Found Steam directory at /var/home/bazzite/.local/share/Steam
Using default Steam Runtime at /var/home/bazzite/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 20 Steam library folders
Steam library folder /run/media/bazzite/f334f0f2-c23a-42e9-b2aa-17f6167eda65 not found. Protontricks might not have access to the directory.
Steam library folder /run/media/bazzite/SD-001 not found. Protontricks might not have access to the directory.
Steam library folder /run/media/bazzite/SD-000 not found. Protontricks might not have access to the directory.
Steam library folder /run/media/bazzite/f334f0f2-c23a-42e9-b2aa-17f6167eda652 not found. Protontricks might not have access to the directory.
Steam library folder /run/media/bazzite/Retro1 not found. Protontricks might not have access to the directory.
Steam library folder /run/media/bazzite/9c0b2b59-8f67-4b97-9bf2-a6960280edf7 not found. Protontricks might not have access to the directory."

**To Reproduce**
1. Run command `protontricks foo bar`
2. Command fails and error is displayed

**Expected behavior**

**System (please complete the following information):**
 - Distro: Bazzite 41
 - Protontricks installation method: installing the beta through the terminal
 - Protontricks version: protontricks (1.11.2.dev+appinfohotfix)
 - Steam version: Steam Deck Stable

**Comment by Matoking** [comment]
"Input/output error" could be related to file system and/or hardware issues.

What output do you get if you run the following command in the terminal (eg. Konsole)?

```sh
$ ls -lha /run/media /run/media/bazzite /run/media/bazzite/DeckBackup
```
