### ISSUE TITLE
issue while trying to $ protontricks 359320 -q --force dotnet40 win7

### ISSUE THREAD

**Issue by Dziban-dev** [Matoking/protontricks#38]
I think i did somthing wrong while installing protontricks or pipx. 

Traceback (most recent call last):
  File "/usr/local/bin/protontricks", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/protontricks/cli.py", line 116, in main
    steam_path, steam_root = find_steam_path()
  File "/usr/local/lib/python3.5/dist-packages/protontricks/steam.py", line 198, in find_steam_path
    if has_steamapps_dir(steam_path):
  File "/usr/local/lib/python3.5/dist-packages/protontricks/steam.py", line 163, in has_steamapps_dir
    os.path.isdir(os.path.join(path, "steamapps"))
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'

**Comment by Matoking** [comment]
Thanks for making an issue report; there was a compatibility issue with Python 3.5.

I've pushed a fix to master now, which you can install by following the "install development version" instructions for pipx in the README. I'll look into making a new release if no new issues appear for a while.
