### ISSUE TITLE
protontricks crashes

### ISSUE THREAD

**Issue by zany130** [Matoking/protontricks#45]
protontricks crashes with the following output 

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/protontricks/gui.py", line 57, in select_steam_app_with_gui
    result = run_zenity(args)
  File "/usr/lib/python3.8/site-packages/protontricks/gui.py", line 36, in run_zenity
    return run(args, check=True, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['zenity', '--forms', '--text=Steam Game Library', '--title=Choose Game', '--add-combo', 'Pick a library game', '--combo-values', 'Batman: Arkham Asylum GOTY Edition: 35140|Batman™: Arkham Knight: 208650|Bully: Scholarship Edition: 12200|CLANNAD: 324160|CLANNAD Side Stories: 420100|Edge Of Eternity: 269190|Fallout: 38400|Fallout 2: 38410|Hyperdimension Neptunia U: Action Unleashed: 387340|If My Heart Had Wings: 326480|KARAKARA: 487430|KARAKARA2: 745850|Lara Croft and the Temple of Osiris: 289690|Left 4 Dead: 500|Legrand Legacy: 556740|Rise of the Tomb Raider: 391220|Sword Art Online: Hollow Realization Deluxe Edition: 607890|The Legend of Heroes: Trails in the Sky: 251150|The Legend of Heroes: Trails in the Sky SC: 251290|The Witcher: Enhanced Edition: 20900|Valkyria Chronicles™: 294860|eden*: 315810']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/protontricks", line 11, in <module>
    load_entry_point('protontricks==1.3.2.dev9+gfc20b09', 'console_scripts', 'protontricks')()
  File "/usr/lib/python3.8/site-packages/protontricks/cli.py", line 171, in main
    steam_app = select_steam_app_with_gui(steam_apps=steam_apps)
  File "/usr/lib/python3.8/site-packages/protontricks/gui.py", line 94, in select_steam_app_with_gui
    raise RuntimeError("Zenity returned an error")
RuntimeError: Zenity returned an error
```

**Comment by zany130** [comment]
i have tried installing the latest git version to and im using manjaro linux

**Comment by lucifertdark** [comment]
I'm getting the same thing on Ubuntu 19.10, running it again straight away makes it work.

**Comment by Matoking** [comment]
Please try copying the following command and running it on the terminal directly:
```
zenity --forms --text='Steam Game Library' --title='Choose Game' --add-combo 'Pick a library game' --combo-values 'Batman: Arkham Asylum GOTY Edition: 35140|Batman™: Arkham Knight: 208650|Bully: Scholarship Edition: 12200|CLANNAD: 324160|CLANNAD Side Stories: 420100|Edge Of Eternity: 269190|Fallout: 38400|Fallout 2: 38410|Hyperdimension Neptunia U: Action Unleashed: 387340|If My Heart Had Wings: 326480|KARAKARA: 487430|KARAKARA2: 745850|Lara Croft and the Temple of Osiris: 289690|Left 4 Dead: 500|Legrand Legacy: 556740|Rise of the Tomb Raider: 391220|Sword Art Online: Hollow Realization Deluxe Edition: 607890|The Legend of Heroes: Trails in the Sky: 251150|The Legend of Heroes: Trails in the Sky SC: 251290|The Witcher: Enhanced Edition: 20900|Valkyria Chronicles™: 294860|eden*: 315810'
```

What does the command print when you run it?

Zenity has had [a bug](https://gitlab.gnome.org/GNOME/zenity/issues/7) for some time where long option lists would cause it to crash when closing down, printing an error message in the process that confuses Protontricks. Very long lists would crash reliably, and shorter lists would only crash intermittently. There is [a workaround in place already](https://github.com/Matoking/protontricks/blob/master/src/protontricks/gui.py#L85), so I'm guessing it's printing a different error message this time around.

**Comment by zany130** [comment]
it  gives this output  
```
zenity --forms --text='Steam Game Library' --title='Choose Game' --add-combo 'Pick a library game' --combo-values 'Batman: Arkham Asylum GOTY Edition: 35140|Batman™: Arkham Knight: 208650|Bully: Scholarship Edition: 12200|CLANNAD: 324160|CLANNAD Side Stories: 420100|Edge Of Eternity: 269190|Fallout: 38400|Fallout 2: 38410|Hyperdimension Neptunia U: Action Unleashed: 387340|If My Heart Had Wings: 326480|KARAKARA: 487430|KARAKARA2: 745850|Lara Croft and the Temple of Osiris: 289690|Left 4 Dead: 500|Legrand Legacy: 556740|Rise of the Tomb Raider: 391220|Sword Art Online: Hollow Realization Deluxe Edition: 607890|The Legend of Heroes: Trails in the Sky: 251150|The Legend of Heroes: Trails in the Sky SC: 251290|The Witcher: Enhanced Edition: 20900|Valkyria Chronicles™: 294860|eden*: 315810'
Gtk-Message: 19:38:46.842: Failed to load module "appmenu-gtk-module"
The Legend of Heroes: Trails in the Sky: 251150
free(): double free detected in tcache 2
Aborted (core dumped)
```

**Comment by Matoking** [comment]
If you installed Protontricks using pipx, please try installing and testing a potential fix I pushed to `zenity_fix` branch:
```
pipx install --force --spec git+https://github.com/Matoking/protontricks.git@zenity_fix protontricks
```

You may need to close and open the terminal emulator before the new version is detected correctly.

**Comment by zany130** [comment]
well i use the version on the aur but i tried installing with pipx like you said and i get this

```
pipx install --force --spec git+https://github.com/Matoking/protontricks.git@zenity_fix protontricks
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall-all,list,run,runpip,ensurepath,completions}
            ...
pipx: error: unrecognized arguments: --spec protontricks
```

**Comment by Matoking** [comment]
Please try this alternative installation method. Open a terminal in your home directory and run the following:

```
python3 -mvenv venv
source venv/bin/activate
pip install git+https://github.com/Matoking/protontricks.git@zenity_fix
venv/bin/protontricks --gui  # or replace with whatever command causes an error
```

After you have tested the fix you can close the terminal and delete the `venv` directory that was created. You might need to install pip and git if you don't have them: `sudo pacman -Syu python-pip git`

**Comment by zany130** [comment]
yup that worked

**Comment by Matoking** [comment]
Awesome, thanks for the help.
