### ISSUE TITLE
Can't intall Protontrics via pipx Ubuntu 20.04

### ISSUE THREAD

**Issue by Sebastian1978** [Matoking/protontricks#55]
See terminal:
$ pipx install protontricks
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/igor/.local/pipx/shared/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/home/igor/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/igor/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/igor/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/igor/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/home/igor/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
ModuleNotFoundError: No module named 'pip._vendor.six'

Error installing protontricks.

**Comment by lucifertdark** [comment]
pipx install git+https://github.com/Matoking/protontricks.git
Traceback (most recent call last):
  File "/home/rob/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/home/rob/.local/lib/python3.8/site-packages/pipx/main.py", line 590, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/rob/.local/lib/python3.8/site-packages/pipx/main.py", line 162, in run_pipx_command
    return commands.install(
  File "/home/rob/.local/lib/python3.8/site-packages/pipx/commands/commands.py", line 38, in install
    package_name = _package_name_from_spec(
  File "/home/rob/.local/lib/python3.8/site-packages/pipx/commands/commands.py", line 100, in _package_name_from_spec
    package_name = venv.install_package_no_deps(
  File "/home/rob/.local/lib/python3.8/site-packages/pipx/venv.py", line 218, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/home/rob/.local/lib/python3.8/site-packages/pipx/venv.py", line 300, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Trying to install the latest dev version give me the above message, Ubuntu 20.04 as well.

**Comment by Sebastian1978** [comment]
I installed by 
python3 -m pip install git+https://github.com/Matoking/protontricks.git
After that no problems

**Comment by Matoking** [comment]
This seems similar to #53 

Did you upgrade to 20.04 from an existing Ubuntu install or is this the first time installing pipx on the system?

**Comment by lucifertdark** [comment]
Upgraded from 19.10, I've now deleted the old copy of protontricks & done a fresh install using the command Sebastian1978 mentioned above & it's all good again. Guess you can call this one closed?

**Comment by Matoking** [comment]
I've looked into this a bit more, and it seems to be related to a Debian-specific patch that's causing grief with pipx and other programs. Since that patch is also inherited by Ubuntu and the derivatives, Ubuntu 20.04 suffers from the same bug. The related issue is pipxproject/pipx#386.

The command mentioned by @Sebastian1978 installs protontricks system-wide if you're not using the `--user` flag. This is *not* recommended, since it can cause issues with the system package manager later on.

---

What this means is that if pipx doesn't work, the best workaround would be to remove pipx and use the normal pip installation method, preferably the one that only installs the utility for the local user:
```
python3 -m pip install --user protontricks
```

This *still* isn't an ideal solution if you're installing multiple Python packages using pip for the same user, but it's probably fine if this is the only time you're doing that.

The other option is to wait until either pipx or Debian comes out with a fix for this issue.

**Comment by axipher** [comment]
Also getting the same error on a fresh Ubuntu 20.04 with Ryzen 3600x + Navi 5700.

I tried using the pipx method and just get roughly the same error as the OP, here's mine in case it's slightly different:

```
axipher@CRUMPET:~$ pipx install protontricks
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/axipher/.local/pipx/shared/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/home/axipher/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/axipher/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/axipher/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/axipher/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/home/axipher/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
ModuleNotFoundError: No module named 'pip._vendor.six'

Error installing protontricks.
```

**Comment by raulcraveiro** [comment]
I have the same problem. I did a fresh install of Ubuntu 20.04.

**Comment by Matoking** [comment]
Can you test whether the following workaround works?

* After installing pipx but before installing protontricks, try running the following command:
```
~/.local/pipx/shared/bin/pip install -I pip
```
* After this, try installing protontricks normally.

---

This workaround is from [one of the comments](https://github.com/pipxproject/pipx/issues/386#issuecomment-618961187) in the upstream issue report mentioned earlier in the thread.

**Comment by raulcraveiro** [comment]
@Matoking Just tried and It worked!

**Comment by Sebastian1978** [comment]
@Matoking For me it worked too! Thanks!

**Comment by axipher** [comment]
> Can you test whether the following workaround works?
> 
> * After installing pipx but before installing protontricks, try running the following command:
> 
> ```
> ~/.local/pipx/shared/bin/pip install -I pip
> ```
> 
> * After this, try installing protontricks normally.
> 
> This workaround is from [one of the comments](https://github.com/pipxproject/pipx/issues/386#issuecomment-618961187) in the upstream issue report mentioned earlier in the thread.

Thanks for the fix!  Worked for me

**Comment by graywolf-theheathen** [comment]
I tried the above with no luck. What I did that worked is this:

python3 -m pip uninstall pipx
delete ~/.local/pipx
Then reinstalled as per the default instructions:
python3 -m pip install --user pipx
~/.local/bin/pipx ensurepath
pipx install protontricks

All was good again then.

**Comment by Birdman7** [comment]
> I tried the above with no luck. What I did that worked is this:
> 
> python3 -m pip uninstall pipx
> delete ~/.local/pipx
> Then reinstalled as per the default instructions:
> python3 -m pip install --user pipx
> ~/.local/bin/pipx ensurepath
> pipx install protontricks
> 
> All was good again then.

Can confirm, this works. Thanks

**Comment by bryceq** [comment]
Installing pipx from the Ubuntu repository fixed the problem for me, but I am not sure if that would (or should) work for everybody.

**Comment by Matoking** [comment]
> Installing pipx from the Ubuntu repository fixed the problem for me, but I am not sure if that would (or should) work for everybody.

The distro's own package manager should be preferred over pip if the package exists there and is up to date. In this case, the commands to run are:

```
sudo apt install pipx
pipx install protontricks
# Upgrade Protontricks when needed
pipx upgrade protontricks
```

pipx seems to be packaged on all mentioned distros except Gentoo (which has an unofficial package already), so this also has the benefit of making the instructions shorter.
