### ISSUE TITLE
protontricks didn't start on Ubuntu 20.04

### ISSUE THREAD

**Issue by JokerGermany** [Matoking/protontricks#59]
Installed the git version with pipx.
When i start protontricks i get the following error:
protontricks 252950 vcrun2017
```
Traceback (most recent call last):
  File "/home/jokergermany/.local/bin/protontricks", line 8, in <module>
    sys.exit(main())
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/cli.py", line 222, in main
    proton_app = find_proton_app(
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 512, in find_proton_app
    proton_app = find_steam_proton_app(
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 424, in find_steam_proton_app
    proton_appid = get_proton_appid(compat_tool_name, appinfo_path)
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 309, in get_proton_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 254, in get_appinfo_sections
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jokergermany/.steam/steam/appcache/appinfo.vdf'
```

**Comment by Matoking** [comment]
Can you check whether the `/home/jokergermany/.steam/steam/appcache/` directory exists? If so, what files does it contain?

`/home/jokergermany/.steam/steam/steamapps` and `/home/jokergermany/.steam/steam/ubuntu12_32` directories should exist at least since Protontricks didn't fail with an "Steam installation not found" error.

**Comment by soredake** [comment]
Latest version of steam installs itself into `debian-installation` folder
![image](https://user-images.githubusercontent.com/5204968/83357604-0135e880-a376-11ea-98a2-7784322f57ef.png)

**Comment by Matoking** [comment]
Closing this issue due to inactivity.
