### ISSUE TITLE
KeyError: 'AccountName'

### ISSUE THREAD

**Issue by bobpaul** [Matoking/protontricks#65]
Providing any arguments other than `--help` or `--version` result in the error below. I'm using protontricks (1.4.1)

```
$ protontricks -s anything
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.1', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.8/site-packages/protontricks/cli.py", line 148, in main
    steam_apps = get_steam_apps(
  File "/usr/lib/python3.8/site-packages/protontricks/steam.py", line 791, in get_steam_apps
    steam_apps += get_custom_windows_shortcuts(steam_path=steam_path)
  File "/usr/lib/python3.8/site-packages/protontricks/steam.py", line 709, in get_custom_windows_shortcuts
    steamid3 = find_current_steamid3(steam_path)
  File "/usr/lib/python3.8/site-packages/protontricks/steam.py", line 664, in find_current_steamid3
    users = [
  File "/usr/lib/python3.8/site-packages/protontricks/steam.py", line 667, in <listcomp>
    "account_name": user_data["AccountName"],
KeyError: 'AccountName'
```
I've tested on 1.4.1
```
$ protontricks --version
protontricks (1.4.1)
```

I've also tested on master:
```
$ protontricks --version
protontricks (1.4.2.dev5+gc77eed7)
```

I am participating in the steam client beta, so maybe this is related to that?

Using `ipdb` I've investigated a bit. Looks like the accountname key is now lowercase, but everything else is still camocase.

```ipdb> vdf_data["users"].items()
dict_items([('1234567890123456', {'accountname': 'MyAccountName', 'PersonaName': 'MyPersona', 'RememberPassword': '1', 'Timestamp': '1600272966', 'WantsOfflineMode': '0', 'mostrecent': '1'}), ]
```

**Comment by Matoking** [comment]
Steam already mixes CamelCase and lowercase in other VDF files depending on the Steam version, so I guess this was only a matter of time as well. :)

I've pushed a commit that *should* fix this into the `account_name_lowercase`. Could you test it and see if there are any lingering issues? If you installed Protontricks using pipx, the following should work:

``` 
pipx install --force git+https://github.com/Matoking/protontricks.git@account_name_lowercase
```

**Comment by bobpaul** [comment]
That works, thanks!
