### ISSUE TITLE
upgrade protontricks failed

### ISSUE THREAD

**Issue by JokerGermany** [Matoking/protontricks#67]
Ubuntu Mate 20.04
```
pipx upgrade protontricks
Traceback (most recent call last):
  File "/home/jokergermany/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/home/jokergermany/.local/lib/python3.8/site-packages/pipx/main.py", line 580, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/jokergermany/.local/lib/python3.8/site-packages/pipx/main.py", line 180, in run_pipx_command
    return commands.upgrade(
  File "/home/jokergermany/.local/lib/python3.8/site-packages/pipx/commands/upgrade.py", line 33, in upgrade
    package_metadata = venv.package_metadata[package]
KeyError: 'protontricks'

```

**Comment by Matoking** [comment]
Try upgrading pipx by running the following command:

```
python3 -m pip install --upgrade --user pipx
```

If that doesn't help with the problem, uninstall Protontricks and try again:

```
pipx uninstall protontricks
pipx install protontricks # or use a different command as described in README
```

**Comment by JokerGermany** [comment]
Thanks, this solved my issue, i will make another one for another problem^
