### ISSUE TITLE
protontricks throws exception on every command

### ISSUE THREAD

**Issue by NLDev** [Matoking/protontricks#69]
**Describe the bug**
I followed the ReadMe's installation guide using Pipx. 
Then I wanted to try it by writing `protontricks -s Squad` and instantly run into an exception: 

```
Traceback (most recent call last):
  File "/usr/local/bin/protontricks", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'protontricks==1.4.1' distribution was not found and is required by the application
```

Other commands such as `protontricks --version` fail as well. 

**System:**
 - Distro: KDE Neon 5.19 (Based on Ubuntu 20.04)
 - Protontricks version: Can't run that command. But assuming it's the latest version to date. 
 - Steam version: Steam Beta (Package Version: 1602258658; API Version: v020) - although shouldn't be necessary. 

Any help would be appreciated :) 
<sub>Unfortunately I'm not a Python dev so I'm not quite sure whats going on...</sub>

**Comment by Matoking** [comment]
Did you try installing Protontricks using some other method than pipx first? `/usr/local/bin/protontricks` is a system-wide location, while pipx is only supposed to install Protontricks for the current user.

**Comment by NLDev** [comment]
Not that I know of. Maybe it got installed as a dependency of some proton tool. I experimented quite a bit with some. 
I just tried `pipx uninstall protontricks` but I'm still able to run the `protontricks` command. (Which results in the same error as above). Ill try and get rid of the systemwide installation. Thanks!
