### ISSUE TITLE
I do a have a dumb is do yes

### ISSUE THREAD

**Issue by nonetrix** [Matoking/protontricks#80]
**Describe the bug**

**To Reproduce**
1. install debnyan gnu/linux
2. run **pipx install protontricks**
3. error

**Expected behavior**
it installs

**System (please complete the following information):**
 - Distro: debnyan sid
 - ???
 - nop
**Additional context**
error message:
Traceback (most recent call last):.
  File "/usr/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.12.3.1', 'console_scripts', 'pipx')()
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 147, in run_pipx_command
    commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands.py", line 312, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "/usr/lib/python3/dist-packages/pipx/Venv.py", line 65, in get_venv_metadata_for_package
    data = json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**

For example, if the command that causes the error is `protontricks 42 faudio`, run `protontricks -v 42 faudio` instead and copy the output here.

**Comment by Matoking** [comment]
This seems to be similar to #73. Can you check if the following command fixes the problem:

```
$ python3 -m pip install --upgrade --user pipx
$ pipx install protontricks # Installation should now work
```

**Comment by Matoking** [comment]
I've examined the issue further, and it seems like Debian Sid ships both Python 3.9 and pipx 0.12.3.1. That version of pipx is too old and isn't supported in Python 3.9.

You can find an existing Debian bug report [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976146).

---

As a workaround, you can use the command I described above. This should install a user-specific version of pipx, which should work until the upstream issue has been fixed.

**Comment by Matoking** [comment]
Closing due to inactivity.
