### ISSUE TITLE
Getting an error when attempting to run proton tricks

### ISSUE THREAD

**Issue by dylanmtaylor** [Matoking/protontricks#87]
I'm on Arch Linux (fully up to date) using non-Flatpak Steam and have winetricks installed. When I run protontricks (trying to get Persona 4 Golden working) I get this traceback:

➜  ~ protontricks 1113000 wmp9 devnum quarts lavfilters

Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.3', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 260, in main
    run_command(
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 221, in run_command
    get_runtime_library_paths(steam_runtime_path, proton_app)
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 61, in get_runtime_library_paths
    runtime_root = next(
StopIteration

**Comment by Infernales** [comment]
Same.
`Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.3', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 267, in main
    run_command(
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 221, in run_command
    get_runtime_library_paths(steam_runtime_path, proton_app)
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 61, in get_runtime_library_paths
    runtime_root = next(
StopIteration`

**Comment by REN-aissance** [comment]
Similar issue here when running "protontricks -c 'wine64 uninstaller' 359320" (first step in a tweak to make Elite Dangerous run)
```
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.4.dev9+g5320a65', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 275, in main
    run_command(
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 232, in run_command
    get_runtime_library_paths(steam_runtime_path, proton_app)
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 61, in get_runtime_library_paths
    runtime_root = next(
StopIteration

```

**Comment by void-witch** [comment]
bug is present on fedora 33, python 3.9.1, protontricks (1.4.4.dev4+g0fab781)

```
$ protontricks -c 'wine64 uninstaller' 359320
Traceback (most recent call last):
  File "/home/proxi/.local/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.4.dev4+g0fab781', 'console_scripts', 'protontricks')())
  File "/home/proxi/.local/lib/python3.9/site-packages/protontricks/cli.py", line 267, in main
    run_command(
  File "/home/proxi/.local/lib/python3.9/site-packages/protontricks/util.py", line 232, in run_command
    get_runtime_library_paths(steam_runtime_path, proton_app)
  File "/home/proxi/.local/lib/python3.9/site-packages/protontricks/util.py", line 61, in get_runtime_library_paths
    runtime_root = next(
StopIteration
```

**Comment by Matoking** [comment]
Valve updated Steam Runtime and changed the installation directory hierarchy in the process, meaning Protontricks wasn't able to find the required files anymore.

I've fixed the bug and published a new version of Protontricks. You can already install it using pipx and other packages should hopefully get the new update soon as well.

If you need to use the current version, you can use the `--no-runtime` flag as a workaround until you can update:

```
protontricks --no-runtime <appid> <command>
```

**Comment by void-witch** [comment]
can confirm the fix, ty!
