### ISSUE TITLE
Protontricks crashes with an Error

### ISSUE THREAD

**Issue by ed-gamer** [Matoking/protontricks#89]
Hey there, first i want to thank you for your great Work!
Unfortunately Protontricks crashes when i try to run it:

I Installed it, like you recommended, with `pipx install protontricks`
It is nown in my home-dir under .local/bin/protontricks.

When i try to run it (just an example):
`~/.local/bin$ protontricks 359320 -q dotnet472 win7`

i get the following Error:

```
Traceback (most recent call last):
  File "/home/olaf/.local/bin/protontricks", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'protontricks==1.1.1+3.g06c86eb' distribution was not found and is required by the application
```
Especially the Last Message confused me, i thought i installed protontricks already, with the pipx-command?
May anyone help?
Thank you very much!

**Comment by ed-gamer** [comment]
I was able to install a working Version of Protontricks with pip:
`python3 -m pip install git+https://github.com/Matoking/protontricks.git`
I know that you don't recommend pip, but for me it works perfect.
Issue closed
