### ISSUE TITLE
Proton Experimental does not work

### ISSUE THREAD

**Issue by XakepSDK** [Matoking/protontricks#93]
**Describe the bug**
protontricks fails to work if proton experimental is the default compat tool

**To Reproduce**
1. Run command `protontricks 16450 winecfg`
2. Command fails and error is displayed

**Expected behavior**
Command works

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks version: protontricks (1.4.5.dev5+g935fa16)
 - Steam version: Mar 331 2021 at 23:19:07

**Additional context**
```
protontricks (INFO): Found Steam directory at /home/user/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/user/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: <removed>
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Found active Proton installation: Proton Experimental
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (WARNING): Running Steam Runtime using bwrap containerization. This is an experimental feature and it may still be incompatible in some situations.
If any problems arise, please try running the command again using the `--no-bwrap` flag and make an issue report if the problem only occurs when bwrap is in use.
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.5.dev5+g935fa16', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 280, in main
    run_command(
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 305, in run_command
    wine_bin_dir = create_wine_bin_dir(
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 153, in create_wine_bin_dir
    binaries = list((proton_app.install_path / "dist" / "bin").iterdir())
  File "/usr/lib/python3.9/pathlib.py", line 1149, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/media/data/SteamLibrary/steamapps/common/Proton - Experimental/dist/bin'
```

**Comment by Matoking** [comment]
Proton Experimental changed a directory name in the newest update. I've pushed a fix to master that should fix the issue.

Please let me know if there are any lingering issues.
