### ISSUE TITLE
The location of 'Proton - Experimental' is incorrect on Fedora 33.

### ISSUE THREAD

**Issue by defianceblack** [Matoking/protontricks#94]
**Describe the bug**
`protontricks` can't find `~/.steam/steam/steamapps/common/Proton - Experimental/dist/bin`.

**To Reproduce**
1. Run command `protontricks -c "env | grep WINEPREFIX" 252950`
2. Command fails and error is displayed

**Expected behavior**
`protontricks` finds `~/.steam/steam/steamapps/common/Proton - Experimental/files/bin`.

**System (please complete the following information):**
 - Distro: Fedora 33
 - Protontricks version: 1.4.4
 - Steam version:
   - Steam API: v020
   - Steam package versions: 1616532526
   - Beta: No

**Additional context**

```sh
protontricks (INFO): Found Steam directory at ~/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at ~/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 0 Steam library folders
protontricks (INFO): Currently logged-in Steam user: $NAME
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Found active Proton installation: Proton Experimental
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.4', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 274, in main
    run_command(
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 253, in run_command
    wine_bin_dir = create_wine_bin_dir(proton_app=proton_app)
  File "/usr/lib/python3.9/site-packages/protontricks/util.py", line 124, in create_wine_bin_dir
    binaries = list((proton_app.install_path / "dist" / "bin").iterdir())
  File "/usr/lib64/python3.9/pathlib.py", line 1149, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '~/.steam/steam/steamapps/common/Proton - Experimental/dist/bin'
```

```sh
ls ~/.steam/steam/steamapps/common/Proton\ -\ Experimental/files/bin/
msidb  wine  wine64  wine64-preloader  wine-preloader  wineserver
```

Edit: The traceback is the same after setting `WINE`, `WINETRICKS` and `WINESERVER`.

**Comment by Matoking** [comment]
This was fixed in #93. Version 1.5.0 with the fix in place was released yesterday, although it may take a while before the update is available for your distro.

You can use the instructions in README to install Protontricks using pipx if you want to use the newer version immediately.
